// Real tasks from "Mõtlemine nähtavaks!" workbook, Part 1
// Chapters: Loendamine (pp.4–19), Liitmine (pp.21–29), Lahutamine (pp.32–40)

export const tasks = [
  // ─── LOENDAMINE (Counting) — pp. 4–19 ────────────────────────────────────────
  {
    slug: "loendamine-tapid",
    title: "Dots: How many?",
    titleEt: "Täpid: Mitu?",
    problem: "How many dots do you see in the picture?",
    problemEt: "Mitu täppi on pildil?",
    chapter: "counting",
    chapterOrder: 1,
    operation: "addition",
    gradeMin: 1,
    gradeMax: 3,
    difficulty: "easy",
    answer: "12",
    imageUrl: "/images/tasks/loendamine-tapid.png",
    strategies: [
      {
        name: "Perceptual subitizing",
        nameEt: "Otsene nägemine",
        description: "Immediately recognizing the total quantity without counting: 'I just see 12.'",
        descriptionEt: "Koguse kohene äratundmine ilma loendamiseta: 'Ma lihtsalt näen, et neid on 12.'",
        example: "Sees '12' instantly as a known pattern",
      },
      {
        name: "Conceptual subitizing — groups",
        nameEt: "Kontseptuaalne subitiseerimine — grupid",
        description: "Breaking the image into smaller sub-groups: 'I see a group of 6 and another group of 6 — that's 12.'",
        descriptionEt: "Pildi jagamine väiksemateks algrühmadeks: 'Näen 6-st gruppi ja veel 6-st — kokku 12.'",
        example: "6 + 6 = 12",
      },
      {
        name: "Skip counting",
        nameEt: "Rühmades loendamine",
        description: "Counting by 2s, 3s, or 5s across the image: '2, 4, 6, 8, 10, 12.'",
        descriptionEt: "Loendamine kahe-, kolme- või viiekaupa: '2, 4, 6, 8, 10, 12.'",
        example: "2, 4, 6, 8, 10, 12",
      },
    ],
    facilitation: "Flash the image for 2–3 seconds, then cover it. Ask: 'How many did you see?' Then: 'How did you see it?' Record each student's strategy on the board. Celebrate grouping strategies over one-by-one counting.",
    facilitationEt: "Näita pilti 2–3 sekundit, seejärel kata kinni. Küsi: 'Mitu nägid?' Seejärel: 'Kuidas sa seda nägid?' Kirjuta iga õpilase strateegia tahvlile. Tähista grupistrateegiaid võrreldes ükshaaval loendamisega.",
    commonMisconceptions: [
      "Counting every dot one by one even after seeing the groups — loses efficiency",
      "Double-counting objects that appear in two sub-groups",
    ],
    commonMisconceptionsEt: [
      "Loendatakse iga täpp ükshaaval isegi pärast gruppide nägemist — kaotab tõhususe",
      "Topeltloendamine — objekte, mis kuuluvad kahte alggruppi, loetakse kaks korda",
    ],
    tags: ["loendamine", "counting", "subitiseerimine", "grupid", "täpid"],
    pageRef: 4,
  },
  {
    slug: "loendamine-ohupallid",
    title: "Balloons: How many?",
    titleEt: "Õhupallid: Mitu?",
    problem: "How many balloons do you see in the picture?",
    problemEt: "Mitu õhupalli on pildil?",
    chapter: "counting",
    chapterOrder: 2,
    operation: "addition",
    gradeMin: 1,
    gradeMax: 3,
    difficulty: "easy",
    answer: "14",
    imageUrl: "/images/tasks/loendamine-ohupallid.png",
    strategies: [
      {
        name: "Perceptual subitizing",
        nameEt: "Otsene nägemine",
        description: "Recognizing 14 balloons at a glance as a whole.",
        descriptionEt: "14 õhupalli äratundmine ühe pilguga tervikuna.",
        example: "Sees '14' as a whole",
      },
      {
        name: "Conceptual subitizing — rows",
        nameEt: "Kontseptuaalne subitiseerimine — read",
        description: "'I see two rows of 7 — that's 14.' or 'I see 7 and 7.'",
        descriptionEt: "'Näen kahte 7-st rida — kokku 14.' või 'Näen 7 ja 7.'",
        example: "7 + 7 = 14",
      },
      {
        name: "Skip counting by 2",
        nameEt: "Kahekaupa loendamine",
        description: "Counting pairs of balloons: 2, 4, 6, 8, 10, 12, 14.",
        descriptionEt: "Õhupallipaaride loendamine: 2, 4, 6, 8, 10, 12, 14.",
        example: "2, 4, 6, 8, 10, 12, 14",
      },
    ],
    facilitation: "After flashing, ask: 'Did anyone group them differently?' Draw the groupings students describe. Ask: 'Which way is fastest? Why?'",
    facilitationEt: "Pärast välgatamist küsi: 'Kas keegi grupistsas neid teisiti?' Joonista õpilaste kirjeldatud grupid. Küsi: 'Milline viis on kõige kiirem? Miks?'",
    commonMisconceptions: [
      "Starting to count from 1 rather than recognizing sub-groups",
      "Losing track of which balloons have been counted",
    ],
    commonMisconceptionsEt: [
      "Alustab loendamist 1-st, mitte ei tunne ära algrühmasid",
      "Kaotab arve, milliseid õhupalle on juba loetud",
    ],
    tags: ["loendamine", "counting", "subitiseerimine", "õhupallid", "read"],
    pageRef: 6,
  },
  {
    slug: "loendamine-tammetoud",
    title: "Acorns: How many?",
    titleEt: "Tammetõrud: Mitu?",
    problem: "How many acorns do you see in the picture?",
    problemEt: "Mitu tammetõru on pildil?",
    chapter: "counting",
    chapterOrder: 3,
    operation: "addition",
    gradeMin: 1,
    gradeMax: 3,
    difficulty: "easy",
    answer: "16",
    imageUrl: "/images/tasks/loendamine-tammetoud.png",
    strategies: [
      {
        name: "Perceptual subitizing",
        nameEt: "Otsene nägemine",
        description: "Seeing 16 acorns as a whole unit instantly.",
        descriptionEt: "16 tammetõru nägemine tervikuna kohe.",
        example: "Sees 16 at once",
      },
      {
        name: "4×4 array",
        nameEt: "4×4 hulk",
        description: "'I see 4 rows of 4 — that's 16.' Using the array structure.",
        descriptionEt: "'Näen 4 rida, kumbagi 4 — kokku 16.' Kasutab hulga struktuuri.",
        example: "4 × 4 = 16",
      },
      {
        name: "Two groups of 8",
        nameEt: "Kaks gruppi 8-st",
        description: "'I split them in half: 8 on the left, 8 on the right — 8+8=16.'",
        descriptionEt: "'Jagan pooleks: 8 vasakul, 8 paremal — 8+8=16.'",
        example: "8 + 8 = 16",
      },
    ],
    facilitation: "This image may have a rectangular arrangement. Ask: 'Did anyone see rows and columns?' Introduce the idea that multiplication (4×4) can help with counting.",
    facilitationEt: "See pilt võib olla ristkülikukujulises paigutuses. Küsi: 'Kas keegi nägi ridu ja veerge?' Tutvusta mõtet, et korrutamine (4×4) aitab lugeda.",
    commonMisconceptions: [
      "Counting in an unstructured path and losing place",
      "Seeing 4 rows of 4 but calculating 4+4=8 instead of 4×4=16",
    ],
    commonMisconceptionsEt: [
      "Loendamine struktureerimata teel ja koha kaotamine",
      "Näeb 4 rida, kumbagi 4, kuid arvutab 4+4=8 asemel 4×4=16",
    ],
    tags: ["loendamine", "counting", "tammetõrud", "4x4", "korrutamine"],
    pageRef: 8,
  },
  {
    slug: "loendamine-lilleoied",
    title: "Flowers: How many?",
    titleEt: "Lilleõied: Mitu?",
    problem: "How many flowers do you see in the picture?",
    problemEt: "Mitu lilleõit on pildil?",
    chapter: "counting",
    chapterOrder: 4,
    operation: "addition",
    gradeMin: 1,
    gradeMax: 3,
    difficulty: "easy",
    answer: "18",
    imageUrl: "/images/tasks/loendamine-lilleoied.png",
    strategies: [
      {
        name: "Conceptual subitizing — colour groups",
        nameEt: "Kontseptuaalne subitiseerimine — värvirühmad",
        description: "Grouping by flower colour: 'I see 9 red and 9 yellow — 9+9=18.'",
        descriptionEt: "Grupistamine lille värvuse järgi: 'Näen 9 punast ja 9 kollast — 9+9=18.'",
        example: "9 + 9 = 18",
      },
      {
        name: "3 groups of 6",
        nameEt: "3 gruppi 6-st",
        description: "'I see three bunches of 6 flowers — 6+6+6=18.'",
        descriptionEt: "'Näen kolm kimpu, kumbki 6 lilli — 6+6+6=18.'",
        example: "6 + 6 + 6 = 18",
      },
      {
        name: "Skip counting by 3",
        nameEt: "Kolmekaupa loendamine",
        description: "Counting in groups of 3: 3, 6, 9, 12, 15, 18.",
        descriptionEt: "Loendamine kolmekaupa: 3, 6, 9, 12, 15, 18.",
        example: "3, 6, 9, 12, 15, 18",
      },
    ],
    facilitation: "Flowers may be grouped or coloured to invite specific strategies. Ask: 'Who used colour to help? Who saw bunches?' Compare: is 3×6 the same as 9+9?",
    facilitationEt: "Lilled võivad olla grupitud või värvitud, et kutsuda esile konkreetseid strateegiaid. Küsi: 'Kes kasutas värvi abivahendina? Kes nägi kimpe?' Võrdle: kas 3×6 on sama mis 9+9?",
    commonMisconceptions: [
      "Missing flowers that overlap or are partially hidden",
      "Grouping by colour but then miscounting within a colour group",
    ],
    commonMisconceptionsEt: [
      "Jäetakse vahele lilled, mis kattuvad või on osaliselt peidetud",
      "Grupistab värvuse järgi, kuid loeb valesti ühe värvirühma sees",
    ],
    tags: ["loendamine", "counting", "lilleleõied", "värvid", "grupid"],
    pageRef: 10,
  },
  {
    slug: "loendamine-autod",
    title: "Cars: How many?",
    titleEt: "Autod: Mitu?",
    problem: "How many cars do you see in the picture?",
    problemEt: "Mitu autot on pildil?",
    chapter: "counting",
    chapterOrder: 5,
    operation: "addition",
    gradeMin: 1,
    gradeMax: 3,
    difficulty: "easy",
    answer: "10",
    imageUrl: "/images/tasks/loendamine-autod.png",
    strategies: [
      {
        name: "5 and 5",
        nameEt: "5 ja 5",
        description: "'I see two rows of 5 — 5+5=10.'",
        descriptionEt: "'Näen kahte rida 5-st — 5+5=10.'",
        example: "5 + 5 = 10",
      },
      {
        name: "Perceptual subitizing",
        nameEt: "Otsene nägemine",
        description: "Recognising 10 as a whole unit — a known ten.",
        descriptionEt: "10 äratundmine tervikuna — tuntud kümne.",
        example: "Ten is a known anchor",
      },
      {
        name: "Skip counting by 2",
        nameEt: "Kahekaupa loendamine",
        description: "Counting pairs: 2, 4, 6, 8, 10.",
        descriptionEt: "Paaride loendamine: 2, 4, 6, 8, 10.",
        example: "2, 4, 6, 8, 10",
      },
    ],
    facilitation: "Ten is a landmark number — celebrate students who recognise it instantly. Ask: 'How do you know it's 10 without counting?' Connect to the ten-frame.",
    facilitationEt: "Kümme on ankruarv — tähista õpilasi, kes tunnevad selle kohe ära. Küsi: 'Kuidas tead, et neid on 10, ilma loendamata?' Seo kümneraamiga.",
    commonMisconceptions: [
      "Not recognising 10 as a landmark — insisting on counting one by one",
    ],
    commonMisconceptionsEt: [
      "10 ei tunta ära ankruarvuna — nõutakse ükshaaval loendamist",
    ],
    tags: ["loendamine", "counting", "autod", "kümme", "ankruarv"],
    pageRef: 12,
  },
  {
    slug: "loendamine-avokaadod",
    title: "Avocados: How many?",
    titleEt: "Avokaadod: Mitu?",
    problem: "How many avocados do you see in the picture?",
    problemEt: "Mitu avokaadot on pildil?",
    chapter: "counting",
    chapterOrder: 6,
    operation: "addition",
    gradeMin: 1,
    gradeMax: 3,
    difficulty: "medium",
    answer: "20",
    imageUrl: "/images/tasks/loendamine-avokaadod.png",
    strategies: [
      {
        name: "4 groups of 5",
        nameEt: "4 gruppi 5-st",
        description: "'I see four clusters of 5 — 5+5+5+5=20.' or 4×5=20.",
        descriptionEt: "'Näen nelja 5-st rühma — 5+5+5+5=20.' või 4×5=20.",
        example: "4 × 5 = 20",
      },
      {
        name: "Two tens",
        nameEt: "Kaks kümmet",
        description: "'I see 10 on the left and 10 on the right — 10+10=20.'",
        descriptionEt: "'Näen vasakul 10 ja paremal 10 — 10+10=20.'",
        example: "10 + 10 = 20",
      },
      {
        name: "Skip counting by 5",
        nameEt: "Viiekaupa loendamine",
        description: "Counting in fives: 5, 10, 15, 20.",
        descriptionEt: "Loendamine viiekaupa: 5, 10, 15, 20.",
        example: "5, 10, 15, 20",
      },
    ],
    facilitation: "20 is a natural stepping-stone to multiplication. When students say '4×5', write it on the board. Ask: 'Did anyone think of it as multiplication?'",
    facilitationEt: "20 on loomulik samm korrutamise suunas. Kui õpilased ütlevad '4×5', kirjuta see tahvlile. Küsi: 'Kas keegi mõtles sellele kui korrutamisele?'",
    commonMisconceptions: [
      "Grouping into 4 fives but adding incorrectly: 5+5=10, 10+5=14, 14+5=18",
    ],
    commonMisconceptionsEt: [
      "Grupistab neljaks viieseks, aga liidab valesti: 5+5=10, 10+5=14, 14+5=18",
    ],
    tags: ["loendamine", "counting", "avokaadod", "20", "viiekaupa", "korrutamine"],
    pageRef: 14,
  },
  {
    slug: "loendamine-marjad",
    title: "Berries: How many?",
    titleEt: "Marjad: Mitu?",
    problem: "How many berries do you see in the picture?",
    problemEt: "Mitu marja on pildil?",
    chapter: "counting",
    chapterOrder: 7,
    operation: "addition",
    gradeMin: 1,
    gradeMax: 4,
    difficulty: "medium",
    answer: "15",
    imageUrl: "/images/tasks/loendamine-marjad.png",
    strategies: [
      {
        name: "3 groups of 5",
        nameEt: "3 gruppi 5-st",
        description: "'I see three bunches of 5 berries — 3×5=15.'",
        descriptionEt: "'Näen kolm kobarata, kumbki 5 marja — 3×5=15.'",
        example: "3 × 5 = 15",
      },
      {
        name: "10 and 5",
        nameEt: "10 ja 5",
        description: "'I see a group of 10 and a group of 5 — 10+5=15.'",
        descriptionEt: "'Näen 10-st gruppi ja 5-st gruppi — 10+5=15.'",
        example: "10 + 5 = 15",
      },
      {
        name: "Skip counting by 5",
        nameEt: "Viiekaupa loendamine",
        description: "5, 10, 15.",
        descriptionEt: "5, 10, 15.",
        example: "5, 10, 15",
      },
    ],
    facilitation: "Ask: 'Is 3×5 the same as 5×3?' Use this to introduce commutativity naturally. Students who say '5, 10, 15' are using multiplication thinking.",
    facilitationEt: "Küsi: 'Kas 3×5 on sama mis 5×3?' Kasuta seda kommutatiivsuse loomuliku tutvustamiseks. Õpilased, kes ütlevad '5, 10, 15', kasutavad korrutamise mõtlemist.",
    commonMisconceptions: [
      "Seeing 3 groups but counting each group as 5 starting from 1 each time (losing the running total)",
    ],
    commonMisconceptionsEt: [
      "Näeb 3 gruppi, kuid loendab iga gruppi algusest (1-st) — kaotab jooksva kokku",
    ],
    tags: ["loendamine", "counting", "marjad", "15", "viiekaupa", "kommutatiivsus"],
    pageRef: 16,
  },
  {
    slug: "loendamine-liblikad",
    title: "Butterflies: How many?",
    titleEt: "Liblikad: Mitu?",
    problem: "How many butterflies do you see in the picture?",
    problemEt: "Mitu liblikat on pildil?",
    chapter: "counting",
    chapterOrder: 8,
    operation: "addition",
    gradeMin: 2,
    gradeMax: 4,
    difficulty: "medium",
    answer: "24",
    imageUrl: "/images/tasks/loendamine-liblikad.png",
    strategies: [
      {
        name: "4 rows of 6",
        nameEt: "4 rida 6-st",
        description: "'I see 4 rows, each with 6 butterflies — 4×6=24.'",
        descriptionEt: "'Näen 4 rida, kumbki 6 liblikat — 4×6=24.'",
        example: "4 × 6 = 24",
      },
      {
        name: "Double 12",
        nameEt: "12 kahekordistamine",
        description: "'I see the top half (12) and bottom half (12) — 12+12=24.'",
        descriptionEt: "'Näen ülemist poolt (12) ja alumist poolt (12) — 12+12=24.'",
        example: "12 + 12 = 24",
      },
      {
        name: "Skip counting by 6",
        nameEt: "Kuuekaupa loendamine",
        description: "6, 12, 18, 24.",
        descriptionEt: "6, 12, 18, 24.",
        example: "6, 12, 18, 24",
      },
    ],
    facilitation: "24 is a rich number with many factors. Ask: 'Is there another way to group these that gives the same answer?' Explore 3×8=24, 4×6=24, 2×12=24.",
    facilitationEt: "24-l on palju tegureid. Küsi: 'Kas on veel viis grupistada, mis annab sama vastuse?' Uurige 3×8=24, 4×6=24, 2×12=24.",
    commonMisconceptions: [
      "Seeing 4 rows of 6 but calculating 4+6=10 instead of 4×6=24",
      "Losing count midway when skip-counting by 6",
    ],
    commonMisconceptionsEt: [
      "Näeb 4 rida, kumbki 6, kuid arvutab 4+6=10 asemel 4×6=24",
      "Kaotab arve kuuekaupa loendamise keskel",
    ],
    tags: ["loendamine", "counting", "liblikad", "24", "kuuekaupa", "korrutamine"],
    pageRef: 18,
  },

  // ─── LIITMINE (Addition) — pp. 21–29 ─────────────────────────────────────────
  {
    slug: "liitmine-7-plus-6",
    title: "7 + 6",
    titleEt: "7 + 6",
    problem: "What is 7 + 6?",
    problemEt: "Mis on 7 + 6?",
    chapter: "addition",
    chapterOrder: 1,
    operation: "addition",
    gradeMin: 1,
    gradeMax: 2,
    difficulty: "easy",
    answer: "13",
    strategies: [
      {
        name: "Doubles plus 1",
        nameEt: "Paaritud pluss 1",
        description: "6+6=12, then add 1 more: 12+1=13. Or: 7+7=14, minus 1=13.",
        descriptionEt: "6+6=12, siis lisa 1: 12+1=13. Või: 7+7=14, miinus 1=13.",
        example: "6+6=12 → 12+1=13",
      },
      {
        name: "Making ten",
        nameEt: "Kümne täiendamine",
        description: "7 needs 3 to make 10. Take 3 from 6: 7+3=10, then 10+3=13.",
        descriptionEt: "7 vajab 3, et saada 10. Võta 6-st 3: 7+3=10, siis 10+3=13.",
        example: "7+3=10, then 10+3=13",
      },
      {
        name: "Counting on",
        nameEt: "Edasi loendamine",
        description: "Start at 7, count on 6: 8, 9, 10, 11, 12, 13.",
        descriptionEt: "Alusta 7-st, loendu 6 võrra edasi: 8, 9, 10, 11, 12, 13.",
        example: "7 → 8, 9, 10, 11, 12, 13",
      },
    ],
    facilitation: "Use ten-frames. Show 7+6 physically: move dots to fill the first frame. Ask: 'Who noticed 7 is close to 10?' This problem is perfect for introducing making-ten.",
    facilitationEt: "Kasuta kümneraamistikke. Näita 7+6 füüsiliselt: liiguta punkte esimese raami täitmiseks. Küsi: 'Kes märkas, et 7 on lähedal 10-le?' See ülesanne on ideaalne kümne täiendamise tutvustamiseks.",
    commonMisconceptions: [
      "Starting count-on from 6 instead of 7 — counting 6 as the first step",
      "Making ten: taking 3 from 6, then adding all of 6 instead of just 3: 7+3=10, then 10+6=16",
    ],
    commonMisconceptionsEt: [
      "Alustab loendamist 6-st asemel 7-st — loeb 6-t esimese sammuna",
      "Kümne täiendamine: võtab 6-st 3, siis liidab kogu 6 asemel ainult 3: 7+3=10, siis 10+6=16",
    ],
    tags: ["liitmine", "addition", "paaritud", "kümne-täiendamine", "1-klass", "2-klass"],
    pageRef: 21,
  },
  {
    slug: "liitmine-12-plus-17",
    title: "12 + 17",
    titleEt: "12 + 17",
    problem: "What is 12 + 17?",
    problemEt: "Mis on 12 + 17?",
    chapter: "addition",
    chapterOrder: 2,
    operation: "addition",
    gradeMin: 1,
    gradeMax: 3,
    difficulty: "easy",
    answer: "29",
    strategies: [
      {
        name: "Place value decomposition",
        nameEt: "Kohaväärtuslahutamine",
        description: "Tens: 10+10=20. Ones: 2+7=9. Total: 20+9=29.",
        descriptionEt: "Kümnetes: 10+10=20. Ühtedes: 2+7=9. Kokku: 20+9=29.",
        example: "10+10=20, 2+7=9 → 29",
      },
      {
        name: "Counting on from the larger",
        nameEt: "Edasi loendamine suuremast",
        description: "Start at 17, count on 12: jump +10=27, +2=29.",
        descriptionEt: "Alusta 17-st, loendu 12 võrra edasi: hüppa +10=27, +2=29.",
        example: "17 → +10 → 27 → +2 → 29",
      },
      {
        name: "Near doubles",
        nameEt: "Peaaegu paaritud",
        description: "12+12=24 (known double), then +5=29. Or 17+17=34, minus 5=29.",
        descriptionEt: "12+12=24 (tuntud paaritud), siis +5=29. Või 17+17=34, miinus 5=29.",
        example: "12+12=24 → 24+5=29",
      },
    ],
    facilitation: "No regrouping needed — this is a great first place-value problem. Ask students to explain how they separated the tens and ones. Draw the decomposition visually.",
    facilitationEt: "Üleminekut pole vaja — see on suurepärane esimene kohaväärtusprobleem. Palu õpilastel selgitada, kuidas nad kümneid ja ühtesid eraldnesid. Joonista lahutamine visuaalselt.",
    commonMisconceptions: [
      "Adding all digits without place value: 1+2+1+7=11",
      "Counting on from 12 instead of 17 (starting from the smaller)",
    ],
    commonMisconceptionsEt: [
      "Liidetakse kõik numbrid ilma kohaväärtuseta: 1+2+1+7=11",
      "Loendamine alates 12-st, mitte 17-st (alustab väiksemast)",
    ],
    tags: ["liitmine", "addition", "kohaväärtuslahutamine", "2-kohaline", "1-klass"],
    pageRef: 23,
  },
  {
    slug: "liitmine-27-plus-35",
    title: "27 + 35",
    titleEt: "27 + 35",
    problem: "What is 27 + 35?",
    problemEt: "Mis on 27 + 35?",
    chapter: "addition",
    chapterOrder: 3,
    operation: "addition",
    gradeMin: 2,
    gradeMax: 4,
    difficulty: "medium",
    answer: "62",
    strategies: [
      {
        name: "Place value decomposition",
        nameEt: "Kohaväärtuslahutamine",
        description: "20+30=50, 7+5=12, 50+12=62.",
        descriptionEt: "20+30=50, 7+5=12, 50+12=62.",
        example: "20+30=50, 7+5=12 → 62",
      },
      {
        name: "Compensation",
        nameEt: "Kompensatsioon",
        description: "27+35 → 27+3=30 (friendly), 30+35=65, 65-3=62. Or: 30+35=65, 65-3=62.",
        descriptionEt: "27+35 → 27+3=30 (mugav), 30+35=65, 65-3=62. Või: 30+35=65, 65-3=62.",
        example: "30+35=65 → 65-3=62",
      },
      {
        name: "Jump strategy",
        nameEt: "Hüppemeetod",
        description: "Start at 27, jump +30=57, then +5=62.",
        descriptionEt: "Alusta 27-st, hüppa +30=57, siis +5=62.",
        example: "27 → +30 → 57 → +5 → 62",
      },
    ],
    facilitation: "First problem requiring regrouping in ones (7+5=12). Ask: 'When you added 7 and 5, what did you do with the extra 10?' Compare place value and jump strategies on a number line.",
    facilitationEt: "Esimene ülesanne, kus on vaja ühtede üleminekut (7+5=12). Küsi: 'Kui liitsid 7 ja 5, mida tegid lisandunud 10-ga?' Võrdle kohaväärtuslahutamist ja hüppemeetodit arvuteljel.",
    commonMisconceptions: [
      "7+5=12 recorded as just 2, dropping the ten",
      "Jump: jumping 35 as a single jump without decomposing into 30+5",
    ],
    commonMisconceptionsEt: [
      "7+5=12 kirjutatakse kui 2, kümme jäetakse ära",
      "Hüppemeetod: hüpatakse 35 ühe hüppena ilma 30+5-ks lahutamata",
    ],
    tags: ["liitmine", "addition", "üleminek", "2-kohaline", "kompensatsioon", "hüppemeetod"],
    pageRef: 25,
  },
  {
    slug: "liitmine-349-plus-36",
    title: "349 + 36",
    titleEt: "349 + 36",
    problem: "What is 349 + 36?",
    problemEt: "Mis on 349 + 36?",
    chapter: "addition",
    chapterOrder: 4,
    operation: "addition",
    gradeMin: 3,
    gradeMax: 5,
    difficulty: "medium",
    answer: "385",
    strategies: [
      {
        name: "Jump strategy",
        nameEt: "Hüppemeetod",
        description: "349+30=379, then 379+6=385.",
        descriptionEt: "349+30=379, siis 379+6=385.",
        example: "349 → +30 → 379 → +6 → 385",
      },
      {
        name: "Compensation",
        nameEt: "Kompensatsioon",
        description: "349 is 1 less than 350. 350+36=386, minus 1=385.",
        descriptionEt: "349 on 1 vähem kui 350. 350+36=386, miinus 1=385.",
        example: "350+36=386 → 386-1=385",
      },
      {
        name: "Place value decomposition",
        nameEt: "Kohaväärtuslahutamine",
        description: "349+30=379 (add tens), 379+6=385 (add ones).",
        descriptionEt: "349+30=379 (liida kümneid), 379+6=385 (liida ühtesid).",
        example: "349+30=379, 379+6=385",
      },
    ],
    facilitation: "3-digit plus 2-digit — good for showing compensation. Ask: 'How close is 349 to 350? Does that help?' Have students explain why they choose which number to make friendly.",
    facilitationEt: "3-kohaline pluss 2-kohaline — hea kompensatsiooni näitamiseks. Küsi: 'Kui lähedal on 349 arvule 350? Kas see aitab?' Palu õpilastel selgitada, miks nad valisid konkreetse arvu mugavaks muutmiseks.",
    commonMisconceptions: [
      "Adding 36 to 349 ones first: 9+6=15, forgetting to carry properly into hundreds",
      "Compensation: 350+36=386 but then subtracting 2 instead of 1",
    ],
    commonMisconceptionsEt: [
      "Liidab 36 juurde 349 ühtesid kõigepealt: 9+6=15, unustab korralikult sadadesse kanda",
      "Kompensatsioon: 350+36=386, aga siis lahutab 2 asemel 1",
    ],
    tags: ["liitmine", "addition", "3-kohaline", "kompensatsioon", "hüppemeetod"],
    pageRef: 27,
  },
  {
    slug: "liitmine-349-plus-156",
    title: "349 + 156",
    titleEt: "349 + 156",
    problem: "What is 349 + 156?",
    problemEt: "Mis on 349 + 156?",
    chapter: "addition",
    chapterOrder: 5,
    operation: "addition",
    gradeMin: 3,
    gradeMax: 6,
    difficulty: "hard",
    answer: "505",
    strategies: [
      {
        name: "Place value decomposition",
        nameEt: "Kohaväärtuslahutamine",
        description: "300+100=400, 40+50=90, 9+6=15. 400+90=490, 490+15=505.",
        descriptionEt: "300+100=400, 40+50=90, 9+6=15. 400+90=490, 490+15=505.",
        example: "300+100=400, 40+50=90, 9+6=15 → 505",
      },
      {
        name: "Compensation",
        nameEt: "Kompensatsioon",
        description: "349+1=350. 350+156=506. 506-1=505.",
        descriptionEt: "349+1=350. 350+156=506. 506-1=505.",
        example: "350+156=506 → 506-1=505",
      },
      {
        name: "Jump from 349",
        nameEt: "Hüpe 349-st",
        description: "349+100=449, 449+50=499, 499+6=505.",
        descriptionEt: "349+100=449, 449+50=499, 499+6=505.",
        example: "349 → +100 → 449 → +50 → 499 → +6 → 505",
      },
    ],
    facilitation: "Two 3-digit numbers with regrouping in all columns. Ask: 'Which partial sums are tricky?' Watch for students who handle the tens regrouping (90+15) confidently. Compare methods.",
    facilitationEt: "Kaks 3-kohalist arvu üleminekuga kõikides veerudes. Küsi: 'Millised osasummad on keerulised?' Märka õpilasi, kes käsitlevad kümnete üleminekut (90+15) enesekindlalt. Võrdle meetodeid.",
    commonMisconceptions: [
      "Place value: forgetting that 9+6=15 crosses into the tens, writing 400+90+5=495",
      "Compensation: rounding 349 to 350 is +1, but forgetting to subtract 1 at the end",
    ],
    commonMisconceptionsEt: [
      "Kohaväärtuslahutamine: unustatakse, et 9+6=15 ületab kümneid, kirjutatakse 400+90+5=495",
      "Kompensatsioon: 349 ümardamine 350-ks on +1, kuid lõpus unustatakse 1 lahutada",
    ],
    tags: ["liitmine", "addition", "3-kohaline", "üleminek", "kompensatsioon", "kohaväärtuslahutamine"],
    pageRef: 29,
  },

  // ─── LAHUTAMINE (Subtraction) — pp. 32–40 ────────────────────────────────────
  {
    slug: "lahutamine-19-miinus-6",
    title: "19 − 6",
    titleEt: "19 − 6",
    problem: "What is 19 − 6?",
    problemEt: "Mis on 19 − 6?",
    chapter: "subtraction",
    chapterOrder: 1,
    operation: "subtraction",
    gradeMin: 1,
    gradeMax: 2,
    difficulty: "easy",
    answer: "13",
    strategies: [
      {
        name: "Counting back",
        nameEt: "Tagasi loendamine",
        description: "Start at 19, count back 6: 18, 17, 16, 15, 14, 13.",
        descriptionEt: "Alusta 19-st, loendu 6 võrra tagasi: 18, 17, 16, 15, 14, 13.",
        example: "19 → 18, 17, 16, 15, 14, 13",
      },
      {
        name: "Think addition",
        nameEt: "Mõtle liitmisena",
        description: "What do I add to 6 to get 19? 6+3=9, 9+10=19 → 3+10=13.",
        descriptionEt: "Mida pean 6-le liitma, et saada 19? 6+3=9, 9+10=19 → 3+10=13.",
        example: "6+13=19 → answer is 13",
      },
      {
        name: "Place value (ones only)",
        nameEt: "Kohaväärtuslahutamine (ühtedes)",
        description: "19-6: tens stay (10), ones: 9-6=3, so 10+3=13.",
        descriptionEt: "19-6: kümneid ei muutu (10), ühtedes: 9-6=3, seega 10+3=13.",
        example: "10 + (9-6) = 10+3 = 13",
      },
    ],
    facilitation: "A clean entry into subtraction — no regrouping needed. Ask: 'Who counted back? Who thought addition?' Both are valid; help students see think-addition as more efficient for larger numbers.",
    facilitationEt: "Puhas sisenemine lahutamisse — üleminekut pole vaja. Küsi: 'Kes luges tagasi? Kes mõtles liitmisena?' Mõlemad on kehtivad; aita õpilastel näha, et 'mõtle liitmisena' on suuremate arvude puhul tõhusam.",
    commonMisconceptions: [
      "Counting back from 6 to 19 (direction reversed)",
      "Think addition: 6+13=19 correct, but misidentifying 13 as wrong because '19-6 looks like it should be less than 10'",
    ],
    commonMisconceptionsEt: [
      "Loendamine tagasi 6-st 19-ni (suund on vastupidine)",
      "Mõtle liitmisena: 6+13=19 on õige, kuid 13 tunnistatakse valeks, sest '19-6 peaks olema alla 10'",
    ],
    tags: ["lahutamine", "subtraction", "tagasi-loendamine", "mõtle-liitmisena", "1-klass"],
    pageRef: 32,
  },
  {
    slug: "lahutamine-47-miinus-20",
    title: "47 − 20",
    titleEt: "47 − 20",
    problem: "What is 47 − 20?",
    problemEt: "Mis on 47 − 20?",
    chapter: "subtraction",
    chapterOrder: 2,
    operation: "subtraction",
    gradeMin: 1,
    gradeMax: 3,
    difficulty: "easy",
    answer: "27",
    strategies: [
      {
        name: "Remove tens",
        nameEt: "Lahuta kümneid",
        description: "47 has 4 tens and 7 ones. Removing 2 tens leaves 2 tens and 7 ones = 27.",
        descriptionEt: "47-l on 4 kümmet ja 7 üht. 2 kümne eemaldamine jätab 2 kümmet ja 7 üht = 27.",
        example: "4 tens - 2 tens = 2 tens; 2 tens + 7 ones = 27",
      },
      {
        name: "Jump strategy",
        nameEt: "Hüppemeetod",
        description: "47-10=37, then 37-10=27.",
        descriptionEt: "47-10=37, siis 37-10=27.",
        example: "47 → -10 → 37 → -10 → 27",
      },
      {
        name: "Think addition",
        nameEt: "Mõtle liitmisena",
        description: "20+?=47 → 20+27=47.",
        descriptionEt: "20+?=47 → 20+27=47.",
        example: "20+27=47 → answer is 27",
      },
    ],
    facilitation: "Subtracting a round number — the tens digit changes, ones stay the same. Ask: 'Did any ones change? Why not?' This builds place value understanding.",
    facilitationEt: "Ümara arvu lahutamine — kümnete number muutub, ühtede number jääb samaks. Küsi: 'Kas ühed muutusid? Miks mitte?' See arendab kohaväärtuse mõistmist.",
    commonMisconceptions: [
      "Subtracting ones too: 47-20 → 47-2-0 → getting 25",
      "Think addition: 20+7=27, but insisting the answer must include a carry",
    ],
    commonMisconceptionsEt: [
      "Lahutab ka ühtesid: 47-20 → 47-2-0 → saab 25",
      "Mõtle liitmisena: 20+7=27 on õige, kuid nõutakse, et vastus peab sisaldama üleminekut",
    ],
    tags: ["lahutamine", "subtraction", "kümnete-lahutamine", "2-kohaline", "hüppemeetod"],
    pageRef: 34,
  },
  {
    slug: "lahutamine-56-miinus-8",
    title: "56 − 8",
    titleEt: "56 − 8",
    problem: "What is 56 − 8?",
    problemEt: "Mis on 56 − 8?",
    chapter: "subtraction",
    chapterOrder: 3,
    operation: "subtraction",
    gradeMin: 2,
    gradeMax: 3,
    difficulty: "medium",
    answer: "48",
    strategies: [
      {
        name: "Compensation (subtract 10, add 2)",
        nameEt: "Kompensatsioon (lahuta 10, liida 2)",
        description: "56-10=46, then 46+2=48. (Because 8=10-2.)",
        descriptionEt: "56-10=46, siis 46+2=48. (Sest 8=10-2.)",
        example: "56-10=46 → 46+2=48",
      },
      {
        name: "Bridging through ten",
        nameEt: "Kümnese kaudu",
        description: "56-6=50, then 50-2=48.",
        descriptionEt: "56-6=50, siis 50-2=48.",
        example: "56-6=50 → 50-2=48",
      },
      {
        name: "Think addition",
        nameEt: "Mõtle liitmisena",
        description: "8+?=56 → 8+2=10, 10+46=56 → 2+46=48.",
        descriptionEt: "8+?=56 → 8+2=10, 10+46=56 → 2+46=48.",
        example: "8+48=56 → answer is 48",
      },
    ],
    facilitation: "Bridging and compensation are both powerful here. Ask: 'Who went through 50? How?' Draw both paths on a number line. Ask: 'Which feels more natural?'",
    facilitationEt: "Kümnese kaudu ja kompensatsioon on mõlemad siin võimsad. Küsi: 'Kes läks läbi 50? Kuidas?' Joonista mõlemad rajad arvuteljel. Küsi: 'Kumb tundub loomulikum?'",
    commonMisconceptions: [
      "Subtracting ones in wrong order: 8-6=2 instead of dealing with 6-8",
      "Compensation: 56-10=46, then adding 2 more making it 50 (wrong direction)",
    ],
    commonMisconceptionsEt: [
      "Lahutab ühtesid vales järjekorras: 8-6=2 asemel tegeleda 6-8 probleemiga",
      "Kompensatsioon: 56-10=46, siis liidab veel 2, saades 50 (vale suund)",
    ],
    tags: ["lahutamine", "subtraction", "kompensatsioon", "kümnesest-üleminek", "2-kohaline"],
    pageRef: 36,
  },
  {
    slug: "lahutamine-35-miinus-19",
    title: "35 − 19",
    titleEt: "35 − 19",
    problem: "What is 35 − 19?",
    problemEt: "Mis on 35 − 19?",
    chapter: "subtraction",
    chapterOrder: 4,
    operation: "subtraction",
    gradeMin: 2,
    gradeMax: 4,
    difficulty: "medium",
    answer: "16",
    strategies: [
      {
        name: "Compensation (subtract 20, add 1)",
        nameEt: "Kompensatsioon (lahuta 20, liida 1)",
        description: "35-20=15, then 15+1=16. (Because 19=20-1.)",
        descriptionEt: "35-20=15, siis 15+1=16. (Sest 19=20-1.)",
        example: "35-20=15 → 15+1=16",
      },
      {
        name: "Think addition",
        nameEt: "Mõtle liitmisena",
        description: "19+?=35 → 19+1=20, 20+15=35 → 1+15=16.",
        descriptionEt: "19+?=35 → 19+1=20, 20+15=35 → 1+15=16.",
        example: "19 → +1 → 20 → +15 → 35; answer: 16",
      },
      {
        name: "Counting back",
        nameEt: "Tagasi loendamine",
        description: "35-10=25, 25-9=16.",
        descriptionEt: "35-10=25, 25-9=16.",
        example: "35-10=25 → 25-9=16",
      },
    ],
    facilitation: "19 is a compensation magnet. Ask: 'Did 19 remind anyone of 20? How did you use that?' The think-addition jump path (19→20→35) is beautiful on a number line.",
    facilitationEt: "19 on kompensatsioonimagnet. Küsi: 'Kas 19 tuletas kellelegi meelde 20-t? Kuidas kasutasid seda?' Mõtle liitmisena hüpperada (19→20→35) on arvuteljel ilus.",
    commonMisconceptions: [
      "Reversing the subtraction in ones: 9-5=4 instead of regrouping",
      "Compensation: 35-20=15 is correct, but then subtracting another 1 instead of adding: 15-1=14",
    ],
    commonMisconceptionsEt: [
      "Ühtede lahutamise ümberpööramine: 9-5=4 asemel üleminekut kasutada",
      "Kompensatsioon: 35-20=15 on õige, kuid siis lahutab 1 asemel liitmise: 15-1=14",
    ],
    tags: ["lahutamine", "subtraction", "kompensatsioon", "mõtle-liitmisena", "2-kohaline"],
    pageRef: 38,
  },
  {
    slug: "lahutamine-764-miinus-321",
    title: "764 − 321",
    titleEt: "764 − 321",
    problem: "What is 764 − 321?",
    problemEt: "Mis on 764 − 321?",
    chapter: "subtraction",
    chapterOrder: 5,
    operation: "subtraction",
    gradeMin: 3,
    gradeMax: 6,
    difficulty: "hard",
    answer: "443",
    strategies: [
      {
        name: "Place value decomposition",
        nameEt: "Kohaväärtuslahutamine",
        description: "700-300=400, 60-20=40, 4-1=3. Total: 400+40+3=443.",
        descriptionEt: "700-300=400, 60-20=40, 4-1=3. Kokku: 400+40+3=443.",
        example: "700-300=400, 60-20=40, 4-1=3 → 443",
      },
      {
        name: "Think addition",
        nameEt: "Mõtle liitmisena",
        description: "321+?=764. 321+79=400, 400+364=764 → 79+364=443.",
        descriptionEt: "321+?=764. 321+79=400, 400+364=764 → 79+364=443.",
        example: "321 → +79 → 400 → +364 → 764; answer: 443",
      },
      {
        name: "Jump strategy",
        nameEt: "Hüppemeetod",
        description: "764-300=464, 464-20=444, 444-1=443.",
        descriptionEt: "764-300=464, 464-20=444, 444-1=443.",
        example: "764 → -300 → 464 → -20 → 444 → -1 → 443",
      },
    ],
    facilitation: "No regrouping needed — perfect for showing that mental strategies scale to 3-digit numbers. Ask: 'Did you need to regroup? Why not?' Compare place value and jump strategies.",
    facilitationEt: "Üleminekut pole vaja — ideaalne näitamaks, et vaimsed strateegiad töötavad ka 3-kohaliste arvudega. Küsi: 'Kas pidid üleminekut kasutama? Miks mitte?' Võrdle kohaväärtuslahutamist ja hüppemeetodit.",
    commonMisconceptions: [
      "Assuming regrouping is needed because the numbers look big",
      "Place value: 60-20=40 correct but adding up as 400+40+3=4403 (spacing error)",
    ],
    commonMisconceptionsEt: [
      "Eeldatakse, et üleminek on vajalik, sest arvud tunduvad suured",
      "Kohaväärtuslahutamine: 60-20=40 õige, kuid liitmisel 400+40+3=4403 (kirjalik viga)",
    ],
    tags: ["lahutamine", "subtraction", "3-kohaline", "kohaväärtuslahutamine", "mõtle-liitmisena"],
    pageRef: 40,
  },
] as const;
