type Chapter = "subtraction" | "addition" | "multiplication" | "division";
type Operation = Chapter | "mixed";

interface WorkbookIITaskEntry {
  slug: string;
  title: string;
  titleEt: string;
  problemEt: string;
  chapter: Chapter;
  operation: Operation;
  pageRef: number;
  difficulty: "medium" | "hard";
  tags: string[];
  strategyTextEt: string;
  misconceptionsEt: string[];
}

const strategyNamesByOperation: Record<Operation, string[]> = {
  addition: [
    "Arvu tükeldamine",
    "Järkarvude summa",
    "Hinnanguline arvutamine",
    "Joonise või arvtelje kasutamine",
  ],
  subtraction: [
    "Arvu tükeldamine",
    "Lahutamine liitmistehte kaudu",
    "Hinnanguline arvutamine",
    "Joonise või arvtelje kasutamine",
  ],
  multiplication: [
    "Distributiivsuse ja assotsiatiivsuse kasutamine",
    "Korrutamine kui liitmistehe",
    "Arvu tükeldamine",
    "Hinnanguline arvutamine",
  ],
  division: [
    "Tulemuse leidmine korrutamise kaudu",
    "Arvu tükeldamine",
    "Jagamine taandamise või teisendamise kaudu",
    "Hinnanguline arvutamine",
  ],
  mixed: [
    "Joonise või arvtelje kasutamine",
    "Arvu tükeldamine",
    "Algoritmi rakendamine",
    "Hinnanguline arvutamine",
  ],
};

const operationLabelEt: Record<Operation, string> = {
  addition: "liitmine",
  subtraction: "lahutamine",
  multiplication: "korrutamine",
  division: "jagamine",
  mixed: "segatehted",
};

const operationLabelEn: Record<Operation, string> = {
  addition: "addition",
  subtraction: "subtraction",
  multiplication: "multiplication",
  division: "division",
  mixed: "mixed operations",
};

const entries: WorkbookIITaskEntry[] = [
  {
    slug: "lahutamine-kontojaak-valjamakse",
    title: "Account balance after withdrawal",
    titleEt: "Kontojääk peale väljamakset",
    problemEt: "Milline on kontojääk peale väljamakset?",
    chapter: "subtraction",
    operation: "subtraction",
    pageRef: 5,
    difficulty: "medium",
    tags: ["lahutamine", "täisarvud", "raha", "kontojääk", "hinnang"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 5 Algoritmi abil lahutamine. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia. Sama keerukusega lisaülesanded: 646 - 169, 443 - 274, 915 - 626, 733 - 465, 854 - 587. Arvu tükeldamine. Lahutamine liitmistehte kaudu.",
    misconceptionsEt: ["Lahutab järke vales järjekorras.", "Ei seo väljamakset kontojäägi vähenemisega."],
  },
  {
    slug: "lahutamine-684-297-hinnang",
    title: "Estimate 684 minus 297",
    titleEt: "Hinnang: 684 - 297",
    problemEt: "Hinda, kas tehte 684 - 297 tulemus on lähemal arvule 300 või arvule 400.",
    chapter: "subtraction",
    operation: "subtraction",
    pageRef: 7,
    difficulty: "medium",
    tags: ["lahutamine", "hinnang", "ümardamine", "684", "297"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 7 Kujutletav kaugus vähendatavast 684. Lahutamine järkarvude summa abil. Metoodiline tähelepanek: kuigi täpset tulemust ei küsita, võib õpilane kasutada strateegiana täpse tulemuse leidmist. Sama keerukusega lisaülesanded: hinda, kas 702 - 458 on üle või alla 250; kas 824 - 596 on lähemal 200 või 300; kas 684 - 297 ligikaudu 500 on tõene; kas 751 - 468 jääb vahemikku 200-300, 300-400 või 400-500. Ümardamine kümnelisteni või sajalisteni. Hinnanguline arvutamine.",
    misconceptionsEt: ["Arvutab täpselt, aga ei otsusta lähimat sadat.", "Ümardab mõlemad arvud nii, et hinnang muutub eksitavaks."],
  },
  {
    slug: "liitmine-kohviku-arve",
    title: "Cafe bill total",
    titleEt: "Kohviku arve",
    problemEt: "Kui palju peab arve järgi kohvikus maksma?",
    chapter: "addition",
    operation: "addition",
    pageRef: 10,
    difficulty: "medium",
    tags: ["liitmine", "kümnendmurrud", "raha", "kohvik", "arve"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 10 Arvteljel kümnendike kujutamine ja liitmine. Järkarvude summa. Sama keerukusega lisaülesanded: 12,6 + 41,3; 33,1 + 15,8; 24,3 + 32,6; 45,4 + 22,2; 61,5 + 18,4. Arvu tükeldamine. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia.",
    misconceptionsEt: ["Joondab kümnendkohad valesti.", "Liidab eurosid ja sente eraldi ilma ühikut kontrollimata."],
  },
  {
    slug: "lahutamine-jootraha",
    title: "Tip from change",
    titleEt: "Jootraha suurus",
    problemEt: "Kati andis 14,3 euro suuruse arve eest teenindajale 15,7 eurot, jättes arve tasumisest ülejääva osa jootrahaks. Kui suur oli jootraha?",
    chapter: "subtraction",
    operation: "subtraction",
    pageRef: 12,
    difficulty: "medium",
    tags: ["lahutamine", "kümnendmurrud", "raha", "jootraha"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 12 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Arvu tükeldamine ja järkarvude summa. Sama keerukusega lisaülesanded: 14,6 - 13,2; 12,8 - 11,5; 18,6 - 17,1; 16,4 - 15,9; 21,3 - 20,7. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia.",
    misconceptionsEt: ["Lahutab väiksema kümnendosa suuremast ilma laenamiseta.", "Ei tõlgenda ülejääki jootrahana."],
  },
  {
    slug: "liitmine-indeksfondi-aktsia",
    title: "Index fund share price",
    titleEt: "Indeksfondi aktsia hind",
    problemEt: "Gregor pani esimesel kuul kõrvale 34,7 eurot, et osta indeksfondi aktsiaid. Kui ta teisel kuul oleks lisanud esimesel kuul säästetule veel 27,8 eurot, oleks ta saanud osta ühe aktsia. Kui palju maksis üks indeksfondi aktsia?",
    chapter: "addition",
    operation: "addition",
    pageRef: 14,
    difficulty: "medium",
    tags: ["liitmine", "kümnendmurrud", "raha", "indeksfond"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 14 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Arvu tükeldamine ja järkarvude summa. Sama keerukusega lisaülesanded: 26,4 + 15,7; 39,7 + 24,6; 72,4 + 18,9; 58,9 + 16,7; 46,8 + 27,5. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia.",
    misconceptionsEt: ["Unustab, et teine summa lisatakse esimesele.", "Joondab kümnendmurrud valesti."],
  },
  {
    slug: "lahutamine-internetimaht",
    title: "Remaining mobile data",
    titleEt: "Allesjäänud internetimaht",
    problemEt: "Telefonipaketis oli 45,6 GB mobiilset internetti. Kuu jooksul kasutati ära 28,7 GB. Kui palju internetimahtu jäi veel alles?",
    chapter: "subtraction",
    operation: "subtraction",
    pageRef: 16,
    difficulty: "medium",
    tags: ["lahutamine", "kümnendmurrud", "mõõtühikud", "GB", "internet"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 16 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Arvu tükeldamine ja järkarvude summa. Sama keerukusega lisaülesanded: 34,7 - 27,8; 63,4 - 25,6; 52,3 - 18,9; 41,5 - 26,7. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia.",
    misconceptionsEt: ["Ei tee kümnendiku kohalt üleminemist.", "Jätab ühiku GB vastuses tähelepanuta."],
  },
  {
    slug: "lahutamine-20-miinus-11-4",
    title: "20 minus 11.4",
    titleEt: "20 - 11,4",
    problemEt: "Mis on tehte tulemus? 20 - 11,4",
    chapter: "subtraction",
    operation: "subtraction",
    pageRef: 18,
    difficulty: "medium",
    tags: ["lahutamine", "kümnendmurrud", "20", "11,4"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 18 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Arvu tükeldamine ja järkarvude summa. Sama keerukusega lisaülesanded: 15 - 6,3; 18 - 9,7; 25 - 12,5; 30 - 14,2. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia.",
    misconceptionsEt: ["Käsitleb 20 kui 2,0.", "Ei kirjuta 20,0 enne kümnendmurru lahutamist."],
  },
  {
    slug: "lahutamine-teravilja-varu",
    title: "Grain left in storage",
    titleEt: "Teravilja osa laos",
    problemEt: "Laos olevast kaubast 5/8 osa on teravilja. Sellest teraviljast 2/8 osa müüakse välismaale. Kui suur osa teravilja jääb peale müüki lattu alles?",
    chapter: "subtraction",
    operation: "subtraction",
    pageRef: 21,
    difficulty: "medium",
    tags: ["lahutamine", "harilikud murrud", "ühenimelised murrud", "teravili"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 21 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 4/5 - 3/5; 6/7 - 4/7; 7/6 - 3/6; 3/4 - 1/4. Lahutamine kasutades liitmistehet. Tagasi loendamine. Algoritmi kasutamine.",
    misconceptionsEt: ["Lahutab nimetajad omavahel.", "Ei erista kogu kauba osa ja teravilja osa."],
  },
  {
    slug: "liitmine-pitsa-kolmandik-kuuendik",
    title: "Pizza fractions eaten",
    titleEt: "Söödud pitsa osa",
    problemEt: "Taavi sõi esmalt tervest pitsast ära kolmandiku ning seejärel veel kuuendiku. Kui suur osa pitsast on söödud Taavi poolt?",
    chapter: "addition",
    operation: "addition",
    pageRef: 23,
    difficulty: "medium",
    tags: ["liitmine", "harilikud murrud", "erinevad nimetajad", "pitsa"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 23 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 1/2 + 1/4; 1/4 + 1/8; 1/5 + 1/10; 1/6 + 1/12. Algoritmi kasutamine. Lühemalt.",
    misconceptionsEt: ["Liidab nimetajad.", "Ei teisenda kolmandikku kuuendikeks."],
  },
  {
    slug: "lahutamine-sokolaad-kolmandik-kuuendik",
    title: "Compare chocolate fractions",
    titleEt: "Šokolaadi koguste vahe",
    problemEt: "Mari sõi šokolaaditahvlist ära kolmandiku ja Tanel kuuendiku. Kui palju rohkem sõi Mari šokolaadi võrreldes Taneli söödud kogusega?",
    chapter: "subtraction",
    operation: "subtraction",
    pageRef: 25,
    difficulty: "medium",
    tags: ["lahutamine", "harilikud murrud", "võrdlemine", "šokolaad"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 25 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 1/2 - 1/4; 1/4 - 1/8; 1/5 - 1/10; 1/6 - 1/12. Algoritmi kasutamine. Lahutamine liitmistehte abil.",
    misconceptionsEt: ["Võrdleb ainult nimetajaid.", "Ei leia ühist nimetajat enne lahutamist."],
  },
  {
    slug: "lahutamine-2-3-miinus-1-9",
    title: "Two thirds minus one ninth",
    titleEt: "2/3 - 1/9",
    problemEt: "Mis on tehte tulemus? 2/3 - 1/9",
    chapter: "subtraction",
    operation: "subtraction",
    pageRef: 27,
    difficulty: "medium",
    tags: ["lahutamine", "harilikud murrud", "ühine nimetaja"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 27 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 3/4 - 3/8; 4/5 - 3/10; 4/7 - 1/14; 5/6 - 1/3. Algoritmi kasutamine.",
    misconceptionsEt: ["Lahutab lugejad ja nimetajad eraldi.", "Ei märka, et 2/3 saab teisendada 6/9-ks."],
  },
  {
    slug: "liitmine-1-3-plus-8-9",
    title: "One third plus eight ninths",
    titleEt: "1/3 + 8/9",
    problemEt: "Mis on tehte tulemus? 1/3 + 8/9",
    chapter: "addition",
    operation: "addition",
    pageRef: 29,
    difficulty: "medium",
    tags: ["liitmine", "harilikud murrud", "liigmurd", "ühine nimetaja"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 29 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 1/4 + 7/8; 1/5 + 9/10; 1/6 + 11/12; 1/5 + 9/10. Murru tükeldamine. Algoritmi rakendamine.",
    misconceptionsEt: ["Ei teisenda kolmandikke üheksandikeks.", "Jätab liigmurru tõlgendamata."],
  },
  {
    slug: "lahutamine-2-miinus-4-5",
    title: "Two minus four fifths",
    titleEt: "2 - 4/5",
    problemEt: "Mis on tehte tulemus? 2 - 4/5",
    chapter: "subtraction",
    operation: "subtraction",
    pageRef: 31,
    difficulty: "medium",
    tags: ["lahutamine", "harilikud murrud", "täisarv ja murd"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 31 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 3 - 7/8; 4 - 9/10; 1 - 8/12; 10 - 3/5. Murru tükeldamine. Algoritmi rakendamine. Tulemuse leidmine läbi teisendamise.",
    misconceptionsEt: ["Ei teisenda täisarvu murdosadeks.", "Lahutab ainult 2 - 4 ja jätab nimetaja tähelepanuta."],
  },
  {
    slug: "korrutamine-toolid-5-18",
    title: "Rows of chairs",
    titleEt: "Toolide read",
    problemEt: "Saali paigutatakse viis rida toole nii, et igas reas on 18 tooli. Mitu tooli saali paigutatakse?",
    chapter: "multiplication",
    operation: "multiplication",
    pageRef: 34,
    difficulty: "medium",
    tags: ["korrutamine", "read", "5 korda 18", "toolid"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 34 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 12 * 6; 8 * 12; 4 * 17; 19 * 5. Arvu tükeldamine. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia.",
    misconceptionsEt: ["Liidab 5 + 18 korrutamise asemel.", "Ei tõlgenda ridu võrdsete rühmadena."],
  },
  {
    slug: "korrutamine-kinkekaardid-12-15",
    title: "Gift card total value",
    titleEt: "Kinkekaartide koguväärtus",
    problemEt: "Kooli sponsoreerib teater, mis pakub kooliüritusele auhinnaks 12 kinkekaarti. Ühe kinkekaardi väärtus on 15 eurot. Kui suur on kinkekaartide väärtus kokku?",
    chapter: "multiplication",
    operation: "multiplication",
    pageRef: 36,
    difficulty: "medium",
    tags: ["korrutamine", "raha", "12 korda 15", "kinkekaart"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 36 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 12 * 14; 14 * 16; 16 * 18; 19 * 12. Distributiivsuse ja assotsiatiivsuse kasutamine. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia. Korrutamine kui liitmistehe.",
    misconceptionsEt: ["Ei kasuta 12 * 15 kui võrdseid rühmi.", "Kaotab kümnelised tükeldamisel."],
  },
  {
    slug: "korrutamine-tuuletaskud-1-8",
    title: "Three pastries at 1.8 euros",
    titleEt: "Kolm tuuletaskut",
    problemEt: "Kooli kohvikus maksab üks tuuletasku 1,8 eurot. Õpilane soovib osta kolm tuuletaskut. Kui palju ta nende eest maksma peab?",
    chapter: "multiplication",
    operation: "multiplication",
    pageRef: 39,
    difficulty: "medium",
    tags: ["korrutamine", "kümnendmurrud", "raha", "1,8 korda 3"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 39 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 1,2 * 5; 1,3 * 4; 1,7 * 3; 8,4 * 2; 6,2 * 4. Distributiivsuse ja assotsiatiivsuse kasutamine. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia. Korrutamine kui liitmistehe.",
    misconceptionsEt: ["Paigutab kümnendkoha valesti.", "Ei kontrolli vastust rahalise hinnangu abil."],
  },
  {
    slug: "korrutamine-paakvagunid-12-4",
    title: "Fuel in five tank wagons",
    titleEt: "Kütuse kogus paakvagunites",
    problemEt: "Üks paakvagun mahutab 12,4 tonni kütust. Mitu tonni kütust kokku mahutab viis taolist paakvagunit?",
    chapter: "multiplication",
    operation: "multiplication",
    pageRef: 41,
    difficulty: "medium",
    tags: ["korrutamine", "kümnendmurrud", "mõõtühikud", "12,4 korda 5"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 41 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 1,2 * 5; 1,3 * 4; 1,7 * 3; 8,4 * 2; 6,2 * 4. Distributiivsuse ja assotsiatiivsuse kasutamine. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia.",
    misconceptionsEt: ["Unustab korrutada kõiki viit vagunit.", "Paigutab kümnendkoha hinnanguga vastuollu."],
  },
  {
    slug: "korrutamine-8-korda-1-4",
    title: "Eight times one fourth",
    titleEt: "8 * 1/4",
    problemEt: "Mis on tehte tulemus? 8 * 1/4",
    chapter: "multiplication",
    operation: "multiplication",
    pageRef: 44,
    difficulty: "medium",
    tags: ["korrutamine", "harilikud murrud", "osa arvust"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 44 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 6 * 1/3; 10 * 1/5; 12 * 1/4. Distributiivsuse ja assotsiatiivsuse kasutamine. Korrutamine kui liitmistehe. Algoritmi kasutamine.",
    misconceptionsEt: ["Tõlgendab 1/4 kui nelja, mitte neljandikku.", "Ei lihtsusta tulemust tervikuks."],
  },
  {
    slug: "korrutamine-2-3-korda-3-4",
    title: "Two thirds times three fourths",
    titleEt: "2/3 * 3/4",
    problemEt: "Mis on tehte tulemus? 2/3 * 3/4",
    chapter: "multiplication",
    operation: "multiplication",
    pageRef: 46,
    difficulty: "hard",
    tags: ["korrutamine", "harilikud murrud", "murd korda murd"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 46 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 1/3 * 3/4; 2/3 * 1/4; 3/5 * 3/4. Algoritmi kasutamine.",
    misconceptionsEt: ["Ei näe korrutamist kui osa osast.", "Korrutab valesti või jätab taandamata."],
  },
  {
    slug: "jagamine-opilased-168-7",
    title: "Students per class",
    titleEt: "Õpilasi klassi kohta",
    problemEt: "Gümnaasiumis on 168 õpilast, kes jagunevad seitsme erineva klassi vahel. Mitu õpilast on keskmiselt ühes gümnaasiumi klassis?",
    chapter: "division",
    operation: "division",
    pageRef: 49,
    difficulty: "medium",
    tags: ["jagamine", "keskmine", "168 jagada 7", "õpilased"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 49 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 216 : 6; 144 : 8; 245 : 5; 132 : 6. Distributiivsuse ja assotsiatiivsuse kasutamine. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia. Korduvalt sama liidetava lahutamine. Algoritmi kasutamine. Tulemuse leidmine läbi korrutamistehte.",
    misconceptionsEt: ["Ei tõlgenda jagamist võrdseks jaotamiseks.", "Ei kontrolli tulemust korrutamisega."],
  },
  {
    slug: "jagamine-kommid-192-24",
    title: "Candy bags",
    titleEt: "Kommikottide arv",
    problemEt: "Igasse kommikotti peab panema 24 kommi. Kokku on vaja jaotada 192 kommi. Mitu kommikotti sedasi saadakse?",
    chapter: "division",
    operation: "division",
    pageRef: 51,
    difficulty: "medium",
    tags: ["jagamine", "192 jagada 24", "kommid", "rühmitamine"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 51 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 168 : 21; 180 : 15; 216 : 18. Distributiivsuse ja assotsiatiivsuse kasutamine. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia. Korduvalt sama liidetava lahutamine. Jagamine taandamise kaudu. Tulemuse leidmine läbi korrutamistehte.",
    misconceptionsEt: ["Segab ära kommide arvu kotis ja kottide arvu.", "Ei kasuta korrutamist jagatise kontrolliks."],
  },
  {
    slug: "jagamine-jooks-4-8-3",
    title: "Average running distance",
    titleEt: "Keskmine jooksudistants",
    problemEt: "Harrastussportlane jooksis kolme päevaga kokku 4,8 km. Kui palju jooksis sportlane päevas keskmiselt?",
    chapter: "division",
    operation: "division",
    pageRef: 54,
    difficulty: "medium",
    tags: ["jagamine", "kümnendmurrud", "keskmine", "4,8 jagada 3"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 54 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 3,6 : 3; 6,4 : 4; 7,5 : 5; 5,4 : 6. Arvu tükeldamine. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia. Elulise konteksti lisamine või muutmine. Teisendamine harilikuks murruks. Tulemuse leidmine läbi korrutamistehte. Jagatava korrutamine kümnega ehk kümnendmurru teisendamine täisarvuks.",
    misconceptionsEt: ["Paigutab kümnendkoha valesti.", "Ei jaga kogudistantsi päevade arvuga."],
  },
  {
    slug: "jagamine-31-2-jaga-4",
    title: "31.2 divided by 4",
    titleEt: "31,2 : 4",
    problemEt: "Mis on tehte tulemus? 31,2 : 4",
    chapter: "division",
    operation: "division",
    pageRef: 56,
    difficulty: "medium",
    tags: ["jagamine", "kümnendmurrud", "31,2", "4"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 56 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 18,9 : 3; 22,5 : 5; 19,8 : 6; 24,8 : 8. Arvu tükeldamine. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia. Elulise konteksti lisamine või muutmine. Tulemuse leidmine läbi korrutamistehte. Jagatava korrutamine kümnega ehk kümnendmurru teisendamine täisarvuks.",
    misconceptionsEt: ["Jätab kümnendkoha jagatises nihkesse.", "Ei tükelda 31,2 sobivateks osadeks."],
  },
  {
    slug: "jagamine-7-2-jaga-0-2",
    title: "7.2 divided by 0.2",
    titleEt: "7,2 : 0,2",
    problemEt: "Mis on tehte tulemus? 7,2 : 0,2",
    chapter: "division",
    operation: "division",
    pageRef: 58,
    difficulty: "hard",
    tags: ["jagamine", "kümnendmurrud", "7,2", "0,2", "teisendamine"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 58 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 3,6 : 0,3; 6,4 : 0,4; 5,2 : 0,2; 7,5 : 0,5. Arvu tükeldamine. Hinnanguline arvutamine, näiteks kompensatsioonistrateegia. Tulemuseni jõudmine läbi teisendamise. Jagatava ja jagaja korrutamine kümnega ehk kümnendmurdude teisendamine täisarvuks. Tulemuse leidmine korrutamise kaudu.",
    misconceptionsEt: ["Arvab, et jagamine teeb alati väiksemaks.", "Korrutab ainult jagatavat kümnega, mitte mõlemat arvu."],
  },
  {
    slug: "jagamine-pael-2-5-jaga-2",
    title: "Two fifths divided by two",
    titleEt: "2/5 : 2",
    problemEt: "Atlasspaela pikkusega 2/5 m kasutatakse mänguasja valmistamiseks. Õmblejal oli vaja leida detailide tegemiseks sobilikku paela pikkust ning ta tegi tehte 2/5 : 2. Mis on tehte tulemus?",
    chapter: "division",
    operation: "division",
    pageRef: 61,
    difficulty: "hard",
    tags: ["jagamine", "harilikud murrud", "2/5", "pael"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 61 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 3/4 : 3; 4/7 : 4; 4/5 : 2; 5/8 : 5. Algoritmi kasutamine. Arvu tükeldamine võrdseteks osadeks. Tulemuse leidmine korrutamise kaudu. Tulemuse leidmine teisendamise kaudu.",
    misconceptionsEt: ["Jagab nimetajat ja lugejat mehaaniliselt valesti.", "Ei tõlgenda murdu võrdseteks osadeks jaotatava pikkusena."],
  },
  {
    slug: "jagamine-1-2-jaga-1-4",
    title: "One half divided by one fourth",
    titleEt: "1/2 : 1/4",
    problemEt: "Mis on tehte tulemus? 1/2 : 1/4",
    chapter: "division",
    operation: "division",
    pageRef: 63,
    difficulty: "hard",
    tags: ["jagamine", "harilikud murrud", "murd jagatud murruga", "mahutamine"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 63 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 1/2 : 1/6; 1/2 : 1/8; 1/3 : 1/6. Algoritmi kasutamine. Arvu tükeldamine võrdseteks osadeks. Tulemuse leidmine korrutamise kaudu. Tulemuse leidmine teisendamise kaudu.",
    misconceptionsEt: ["Ei mõtle, mitu neljandikku mahub poolde.", "Rakendab pöördarvu reeglit ilma tähendust kontrollimata."],
  },
  {
    slug: "jagamine-3-4-jaga-1-2",
    title: "Three fourths divided by one half",
    titleEt: "3/4 : 1/2",
    problemEt: "Mis on tehte tulemus? 3/4 : 1/2",
    chapter: "division",
    operation: "division",
    pageRef: 65,
    difficulty: "hard",
    tags: ["jagamine", "harilikud murrud", "murd jagatud murruga", "proportsionaalne mõtlemine"],
    strategyTextEt: "Ülesande lahendusstrateegiaid 65 Jooniste, kujundite või kogumite ette kujutamine ja/või rühmitamine, arvteljel kujutamine. Sama keerukusega lisaülesanded: 2/3 : 1/2; 3/5 : 1/2; 5/6 : 1/2. Algoritmi kasutamine. Arvu mahutamine teise arvu väärtusesse. Tulemuse leidmine korrutamise kaudu. Proportsionaalne mõtlemine. Näiteks ühe euro korral on 3/4 eurot 75 senti ja 1/2 eurot 50 senti. Üks 50-sendine mahub 75 sendi sisse ning üle jääb 25 senti, seega mahub 50 senti 75 sendi sisse 1,5 korda.",
    misconceptionsEt: ["Ei tõlgenda jagamist mahutamisena.", "Arvab, et tulemus ei saa olla ühest suurem."],
  },
];

function strategiesFor(entry: WorkbookIITaskEntry) {
  return strategyNamesByOperation[entry.operation].map((nameEt) => ({
    name: nameEt,
    nameEt,
    description: entry.strategyTextEt,
    descriptionEt: entry.strategyTextEt,
    example: entry.problemEt,
  }));
}

export const workbookIITasks = entries.map((entry, index) => ({
  slug: entry.slug,
  workbookPart: "II" as const,
  title: entry.title,
  titleEt: entry.titleEt,
  problem: entry.problemEt,
  problemEt: entry.problemEt,
  chapter: entry.chapter,
  chapterOrder: index + 1,
  operation: entry.operation,
  gradeMin: 4,
  gradeMax: 6,
  difficulty: entry.difficulty,
  strategies: strategiesFor(entry),
  facilitation: `Use the verified workbook II strategy page for ${operationLabelEn[entry.operation]}. Ask students to explain which representation, decomposition, estimate, or inverse operation makes the task efficient.`,
  facilitationEt: `Kasuta II osa kontrollitud strateegialehte. Fookus: ${operationLabelEt[entry.operation]}. Palu õpilastel selgitada, milline joonis, arvu tükeldamine, hinnang või pöördtehe muudab ülesande tõhusaks. ${entry.strategyTextEt}`,
  commonMisconceptions: entry.misconceptionsEt,
  commonMisconceptionsEt: entry.misconceptionsEt,
  tags: ["II osa", "töövihik II", "arvutaju", ...entry.tags],
  pageRef: entry.pageRef,
}));
