export const tasks = [
  // ─── ADDITION ───────────────────────────────────────────────────────────────
  {
    slug: "liitmine-38-plus-26",
    title: "38 + 26",
    titleEt: "38 + 26",
    problem: "What is 38 + 26?",
    problemEt: "Mis on 38 + 26?",
    operation: "addition",
    gradeMin: 2,
    gradeMax: 3,
    difficulty: "easy",
    answer: "64",
    strategies: [
      {
        name: "Place value decomposition",
        nameEt: "Kohaväärtuslahutamine",
        description: "Break both numbers into tens and ones: 30+8+20+6 = 50+14 = 64",
        descriptionEt: "Lahuta mõlemad arvud kümneteks ja ühtedeks: 30+8+20+6 = 50+14 = 64",
        example: "30+8+20+6 = 50+14 = 64",
      },
      {
        name: "Compensation",
        nameEt: "Kompensatsioon",
        description: "Round 26 up to 30, add: 38+30=68, then subtract 4: 68-4=64",
        descriptionEt: "Ümarda 26 arvuni 30, liida: 38+30=68, lahuta 4: 68-4=64",
        example: "38+30=68 → 68-4=64",
      },
      {
        name: "Making a friendly number",
        nameEt: "Mugava arvu moodustamine",
        description: "Give 2 from 38 to 26: 36+28 → then 36+30-2=64",
        descriptionEt: "Anna 38-st 2 arvule 26: 36+28 → 36+30-2=64",
        example: "38+26 → 36+28 → 36+30-2=64",
      },
    ],
    facilitation: "Ask: 'Did anyone start differently? Can you show us on the number line?' Highlight how compensation avoids regrouping entirely.",
    facilitationEt: "Küsi: 'Kas keegi alustas teisiti? Kas saad näidata arvuteljel?' Rõhuta, kuidas kompensatsioon väldib üleminekut.",
    commonMisconceptions: [
      "Adding tens and ones separately but forgetting to combine: 50+14 stuck at 50+1=51",
      "Forgetting to subtract the amount added during compensation",
    ],
    commonMisconceptionsEt: [
      "Liidab kümneid ja ühtesid eraldi, kuid unustab ühendada: 50+14 jääb 50+1=51 juurde",
      "Unustab kompensatsiooni käigus lisatud arvu lahutada",
    ],
    tags: ["liitmine", "addition", "2-kohaline", "kompensatsioon", "kohaväärtuslahutamine"],
    pageRef: 12,
  },
  {
    slug: "liitmine-57-plus-36",
    title: "57 + 36",
    titleEt: "57 + 36",
    problem: "What is 57 + 36?",
    problemEt: "Mis on 57 + 36?",
    operation: "addition",
    gradeMin: 2,
    gradeMax: 4,
    difficulty: "medium",
    answer: "93",
    strategies: [
      {
        name: "Place value decomposition",
        nameEt: "Kohaväärtuslahutamine",
        description: "50+30=80, 7+6=13, 80+13=93",
        descriptionEt: "50+30=80, 7+6=13, 80+13=93",
        example: "50+30=80, 7+6=13, 80+13=93",
      },
      {
        name: "Jump strategy (number line)",
        nameEt: "Hüppemeetod (arvutelg)",
        description: "Start at 57, jump +30=87, jump +6=93",
        descriptionEt: "Alusta 57-st, hüppa +30=87, hüppa +6=93",
        example: "57 → +30 → 87 → +6 → 93",
      },
      {
        name: "Compensation",
        nameEt: "Kompensatsioon",
        description: "57+36 → 57+40=97 → 97-4=93",
        descriptionEt: "57+36 → 57+40=97 → 97-4=93",
        example: "57+40=97 → 97-4=93",
      },
    ],
    facilitation: "This is a good problem for surfacing the 'crossing the decade' challenge. Ask where students pause — is it at the tens, or combining the partial sums?",
    facilitationEt: "See ülesanne toob hästi esile 'kümnete piiri ületamise' raskuse. Küsi, kus õpilased peatuvad — kümnetel või osasummade liitmisel?",
    commonMisconceptions: [
      "Treating 7+6=13 as just 3, dropping the ten",
      "Jump strategy: jumping 36 as a single jump without decomposing",
    ],
    commonMisconceptionsEt: [
      "Arvestab 7+6=13 kui lihtsalt 3, kaotab kümne",
      "Hüppemeetod: hüppab 36 ühe hüppena ilma lahutamata",
    ],
    tags: ["liitmine", "addition", "2-kohaline", "hüppemeetod", "arvutelg"],
    pageRef: 14,
  },
  {
    slug: "liitmine-248-plus-136",
    title: "248 + 136",
    titleEt: "248 + 136",
    problem: "What is 248 + 136?",
    problemEt: "Mis on 248 + 136?",
    operation: "addition",
    gradeMin: 3,
    gradeMax: 5,
    difficulty: "medium",
    answer: "384",
    strategies: [
      {
        name: "Place value decomposition",
        nameEt: "Kohaväärtuslahutamine",
        description: "200+100=300, 40+30=70, 8+6=14, 300+70+14=384",
        descriptionEt: "200+100=300, 40+30=70, 8+6=14, 300+70+14=384",
        example: "200+100=300, 40+30=70, 8+6=14 → 300+70+14=384",
      },
      {
        name: "Compensation",
        nameEt: "Kompensatsioon",
        description: "248+136 → 250+136=386 → 386-2=384",
        descriptionEt: "248+136 → 250+136=386 → 386-2=384",
        example: "250+136=386 → 386-2=384",
      },
    ],
    facilitation: "Great for showing that mental strategies work even with 3-digit numbers. Push students to articulate *why* they chose to round 248 vs 136.",
    facilitationEt: "Suurepärane näitamaks, et vaimsed strateegiad töötavad ka 3-kohaliste arvudega. Küsi õpilastelt, miks nad ümardasid pigem 248 kui 136.",
    commonMisconceptions: [
      "Partial sum of ones: 8+6=14 recorded as 4, tens carried incorrectly",
    ],
    commonMisconceptionsEt: [
      "Ühtede osasumma: 8+6=14 kirjutatakse kui 4, kümned kantakse valesti üle",
    ],
    tags: ["liitmine", "addition", "3-kohaline", "kompensatsioon"],
    pageRef: 18,
  },
  {
    slug: "liitmine-99-plus-47",
    title: "99 + 47",
    titleEt: "99 + 47",
    problem: "What is 99 + 47?",
    problemEt: "Mis on 99 + 47?",
    operation: "addition",
    gradeMin: 2,
    gradeMax: 4,
    difficulty: "easy",
    answer: "146",
    strategies: [
      {
        name: "Compensation (near-hundred)",
        nameEt: "Kompensatsioon (lähedal sajale)",
        description: "99+47 → 100+47=147 → 147-1=146",
        descriptionEt: "99+47 → 100+47=147 → 147-1=146",
        example: "100+47=147 → 147-1=146",
      },
      {
        name: "Place value decomposition",
        nameEt: "Kohaväärtuslahutamine",
        description: "90+9+40+7 = 130+16 = 146",
        descriptionEt: "90+9+40+7 = 130+16 = 146",
        example: "90+40=130, 9+7=16 → 130+16=146",
      },
    ],
    facilitation: "99 is a classic 'compensation magnet'. Ask: 'Who noticed something special about 99? How did that change your approach?'",
    facilitationEt: "99 on klassikaline 'kompensatsiooni magnet'. Küsi: 'Kes märkas midagi erilist 99 juures? Kuidas see muutis teie lähenemist?'",
    commonMisconceptions: [
      "Adding 1 instead of subtracting 1 after rounding: 100+47=147 → +1=148",
    ],
    commonMisconceptionsEt: [
      "Ümardamise järel liidab 1 asemel lahutab: 100+47=147 → +1=148",
    ],
    tags: ["liitmine", "addition", "kompensatsioon", "lähim-sada"],
    pageRef: 16,
  },

  // ─── SUBTRACTION ─────────────────────────────────────────────────────────────
  {
    slug: "lahutamine-84-miinus-38",
    title: "84 − 38",
    titleEt: "84 − 38",
    problem: "What is 84 − 38?",
    problemEt: "Mis on 84 − 38?",
    operation: "subtraction",
    gradeMin: 2,
    gradeMax: 4,
    difficulty: "medium",
    answer: "46",
    strategies: [
      {
        name: "Think addition (missing addend)",
        nameEt: "Mõtle liitmisena (puuduv liidetav)",
        description: "What do I add to 38 to get 84? 38+2=40, 40+44=84 → 2+44=46",
        descriptionEt: "Mida pean 38-le liitma, et saada 84? 38+2=40, 40+44=84 → 2+44=46",
        example: "38+2=40, 40+44=84 → answer: 46",
      },
      {
        name: "Compensation",
        nameEt: "Kompensatsioon",
        description: "84-38 → 84-40=44 → 44+2=46",
        descriptionEt: "84-38 → 84-40=44 → 44+2=46",
        example: "84-40=44 → 44+2=46",
      },
      {
        name: "Place value decomposition",
        nameEt: "Kohaväärtuslahutamine",
        description: "84-38: 80-30=50, 4-8 needs regrouping → 14-8=6, 50-10=40, 40+6=46",
        descriptionEt: "84-38: 80-30=50, 4-8 vajab üleminekut → 14-8=6, 50-10=40, 40+6=46",
        example: "80-30=50, 14-8=6, 50-10+6=46",
      },
    ],
    facilitation: "This problem beautifully reveals whether students are additive thinkers or purely subtractive. Highlight 'think addition' as the most elegant path.",
    facilitationEt: "See ülesanne näitab selgelt, kas õpilased mõtlevad aditiivselt või ainult subtraktiivselt. Tõsta esile 'mõtle liitmisena' kui kõige elegantsemat teed.",
    commonMisconceptions: [
      "Inverting the ones: 8-4=4 instead of dealing with 4-8",
      "Compensation: forgetting to add back the 2 after subtracting 40",
    ],
    commonMisconceptionsEt: [
      "Pöörab ühtesid: 8-4=4 asemel tegeleda 4-8 probleemiga",
      "Kompensatsioon: unustab 2 tagasi liita pärast 40 lahutamist",
    ],
    tags: ["lahutamine", "subtraction", "2-kohaline", "mõtle-liitmisena", "kompensatsioon"],
    pageRef: 28,
  },
  {
    slug: "lahutamine-143-miinus-78",
    title: "143 − 78",
    titleEt: "143 − 78",
    problem: "What is 143 − 78?",
    problemEt: "Mis on 143 − 78?",
    operation: "subtraction",
    gradeMin: 3,
    gradeMax: 5,
    difficulty: "hard",
    answer: "65",
    strategies: [
      {
        name: "Think addition",
        nameEt: "Mõtle liitmisena",
        description: "78+2=80, 80+20=100, 100+43=143 → 2+20+43=65",
        descriptionEt: "78+2=80, 80+20=100, 100+43=143 → 2+20+43=65",
        example: "78→80→100→143: jumps of 2+20+43=65",
      },
      {
        name: "Compensation",
        nameEt: "Kompensatsioon",
        description: "143-78 → 143-80=63 → 63+2=65",
        descriptionEt: "143-78 → 143-80=63 → 63+2=65",
        example: "143-80=63 → 63+2=65",
      },
    ],
    facilitation: "Use an empty number line on the board. Have students share their jump sequences. Compare the 'think addition' jumps with compensation — both land on 65.",
    facilitationEt: "Kasuta tahvlil tühja arvutelge. Lase õpilastel jagada oma hüppejadasi. Võrdle 'mõtle liitmisena' hüppeid kompensatsiooniga — mõlemad jõuavad 65-ni.",
    commonMisconceptions: [
      "Think addition: miscounting the jumps (especially the final jump to 143)",
      "Compensation: adding instead of subtracting the correction",
    ],
    commonMisconceptionsEt: [
      "Mõtle liitmisena: hüpete vale lugemine (eriti viimane hüpe 143-ni)",
      "Kompensatsioon: paranduse liitmine asemel lahutamist",
    ],
    tags: ["lahutamine", "subtraction", "3-kohaline", "mõtle-liitmisena", "arvutelg"],
    pageRef: 32,
  },
  {
    slug: "lahutamine-1001-miinus-99",
    title: "1001 − 99",
    titleEt: "1001 − 99",
    problem: "What is 1001 − 99?",
    problemEt: "Mis on 1001 − 99?",
    operation: "subtraction",
    gradeMin: 4,
    gradeMax: 6,
    difficulty: "hard",
    answer: "902",
    strategies: [
      {
        name: "Compensation (round the subtrahend)",
        nameEt: "Kompensatsioon (ümarda lahutajat)",
        description: "1001-100=901, then +1=902",
        descriptionEt: "1001-100=901, siis +1=902",
        example: "1001-100=901 → 901+1=902",
      },
      {
        name: "Think addition",
        nameEt: "Mõtle liitmisena",
        description: "99+1=100, 100+900=1000, 1000+1=1001 → 1+900+1=902",
        descriptionEt: "99+1=100, 100+900=1000, 1000+1=1001 → 1+900+1=902",
        example: "99→100→1000→1001: 1+900+1=902",
      },
    ],
    facilitation: "A spectacular compensation problem. Ask students to predict whether the answer is close to 900 or 1000 before calculating — builds estimation sense.",
    facilitationEt: "Suurepärane kompensatsiooniülesanne. Palu õpilastel enne arvutamist ennustada, kas vastus on lähemal 900-le või 1000-le — arendab hindamisvõimet.",
    commonMisconceptions: [
      "1001-99=1001-100=901 (forgetting to add 1 back)",
      "Over-complicating by doing column subtraction mentally",
    ],
    commonMisconceptionsEt: [
      "1001-99=1001-100=901 (unustab 1 tagasi liita)",
      "Keerulisemaks tegemine, tehes vaimselt veerulist lahutamist",
    ],
    tags: ["lahutamine", "subtraction", "4-kohaline", "kompensatsioon", "hindamine"],
    pageRef: 36,
  },
  {
    slug: "lahutamine-63-miinus-27",
    title: "63 − 27",
    titleEt: "63 − 27",
    problem: "What is 63 − 27?",
    problemEt: "Mis on 63 − 27?",
    operation: "subtraction",
    gradeMin: 2,
    gradeMax: 3,
    difficulty: "medium",
    answer: "36",
    strategies: [
      {
        name: "Counting back",
        nameEt: "Tagasi loendamine",
        description: "63-20=43, 43-7=36",
        descriptionEt: "63-20=43, 43-7=36",
        example: "63-20=43 → 43-7=36",
      },
      {
        name: "Think addition",
        nameEt: "Mõtle liitmisena",
        description: "27+3=30, 30+33=63 → 3+33=36",
        descriptionEt: "27+3=30, 30+33=63 → 3+33=36",
        example: "27→30→63: 3+33=36",
      },
      {
        name: "Compensation",
        nameEt: "Kompensatsioon",
        description: "63-30=33, 33+3=36",
        descriptionEt: "63-30=33, 33+3=36",
        example: "63-30=33 → 33+3=36",
      },
    ],
    facilitation: "Good introductory problem for 'think addition'. Use a number line to show the distance between 27 and 63.",
    facilitationEt: "Hea sissejuhatav ülesanne 'mõtle liitmisena' strateegiaks. Kasuta arvutelge, et näidata vahemaad 27 ja 63 vahel.",
    commonMisconceptions: [
      "Counting back by ones from 63 — very slow and error-prone",
      "Reversing the subtraction: 27-23=... (treating smaller digit as minuend)",
    ],
    commonMisconceptionsEt: [
      "Tagasi loendamine ühtede kaupa 63-st — aeglane ja vigaderohke",
      "Lahutamise ümberpööramine: 27-23=... (väiksem arv miinusena)",
    ],
    tags: ["lahutamine", "subtraction", "2-kohaline", "loendamine", "mõtle-liitmisena"],
    pageRef: 26,
  },

  // ─── MULTIPLICATION ──────────────────────────────────────────────────────────
  {
    slug: "korrutamine-6x7",
    title: "6 × 7",
    titleEt: "6 × 7",
    problem: "What is 6 × 7?",
    problemEt: "Mis on 6 × 7?",
    operation: "multiplication",
    gradeMin: 3,
    gradeMax: 4,
    difficulty: "easy",
    answer: "42",
    strategies: [
      {
        name: "Doubling",
        nameEt: "Kahekordistamine",
        description: "3×7=21, double it: 21×2=42",
        descriptionEt: "3×7=21, kahekordista: 21×2=42",
        example: "3×7=21 → 21+21=42",
      },
      {
        name: "Using a known fact",
        nameEt: "Teadaoleva fakti kasutamine",
        description: "5×7=35, +7=42",
        descriptionEt: "5×7=35, +7=42",
        example: "5×7=35 → 35+7=42",
      },
      {
        name: "Decomposition",
        nameEt: "Lahutamine",
        description: "6×7 = 6×5 + 6×2 = 30+12 = 42",
        descriptionEt: "6×7 = 6×5 + 6×2 = 30+12 = 42",
        example: "6×5=30, 6×2=12 → 30+12=42",
      },
    ],
    facilitation: "Ask students which times table they used as a 'stepping stone'. Celebrate multiple routes to 42.",
    facilitationEt: "Küsi õpilastelt, millist korrutustabelit kasutasid 'astmekivina'. Tähista erinevaid teid vastuseni 42.",
    commonMisconceptions: [
      "Confusing 6×7 with 6×8 (=48) — similar-looking facts",
      "Doubling error: 3×7=21 but then adding 21 once more as 21+1=22",
    ],
    commonMisconceptionsEt: [
      "Ajab segi 6×7 ja 6×8 (=48) — sarnased faktid",
      "Kahekordistamise viga: 3×7=21 aga siis liidab 21 veel kord kui 21+1=22",
    ],
    tags: ["korrutamine", "multiplication", "põhifaktid", "kahekordistamine"],
    pageRef: 46,
  },
  {
    slug: "korrutamine-4x25",
    title: "4 × 25",
    titleEt: "4 × 25",
    problem: "What is 4 × 25?",
    problemEt: "Mis on 4 × 25?",
    operation: "multiplication",
    gradeMin: 3,
    gradeMax: 5,
    difficulty: "easy",
    answer: "100",
    strategies: [
      {
        name: "Known relationship (quarters)",
        nameEt: "Teadaolev seos (veerandid)",
        description: "4 × 25 = 100 because four quarters make a whole (100 cents)",
        descriptionEt: "4 × 25 = 100, sest neli veerandit moodustavad terviku (100 senti)",
        example: "4 quarters = 1 euro = 100 cents",
      },
      {
        name: "Halving and doubling",
        nameEt: "Poolitamine ja kahekordistamine",
        description: "4×25 → 2×50 → 1×100",
        descriptionEt: "4×25 → 2×50 → 1×100",
        example: "4×25 → 2×50 → 100",
      },
    ],
    facilitation: "Connect to money: 4 twenty-five-cent coins = 1 euro. Real-world anchors make this fact memorable. Ask if students have a 'trick' for 25s.",
    facilitationEt: "Seo rahaga: 4 kahekümne-viie-sendist münti = 1 euro. Päriselu ankur muudab fakti meeldejäävaks. Küsi, kas õpilastel on 'nipp' 25de jaoks.",
    commonMisconceptions: [
      "4×25=80 (adding 25 only 3 times)",
    ],
    commonMisconceptionsEt: [
      "4×25=80 (liidab 25 ainult 3 korda)",
    ],
    tags: ["korrutamine", "multiplication", "25", "poolitamine", "kahekordistamine"],
    pageRef: 48,
  },
  {
    slug: "korrutamine-12x15",
    title: "12 × 15",
    titleEt: "12 × 15",
    problem: "What is 12 × 15?",
    problemEt: "Mis on 12 × 15?",
    operation: "multiplication",
    gradeMin: 4,
    gradeMax: 6,
    difficulty: "medium",
    answer: "180",
    strategies: [
      {
        name: "Halving and doubling",
        nameEt: "Poolitamine ja kahekordistamine",
        description: "12×15 → 6×30=180",
        descriptionEt: "12×15 → 6×30=180",
        example: "12÷2=6, 15×2=30 → 6×30=180",
      },
      {
        name: "Distributive property",
        nameEt: "Jaotusseadus",
        description: "12×15 = 12×10 + 12×5 = 120+60 = 180",
        descriptionEt: "12×15 = 12×10 + 12×5 = 120+60 = 180",
        example: "12×10=120, 12×5=60 → 120+60=180",
      },
      {
        name: "Using 12 as 10+2",
        nameEt: "12 kui 10+2",
        description: "10×15=150, 2×15=30, 150+30=180",
        descriptionEt: "10×15=150, 2×15=30, 150+30=180",
        example: "10×15=150, 2×15=30 → 180",
      },
    ],
    facilitation: "Halving and doubling is elegant here. Ask: 'How do you know 6×30 is easier than 12×15?' Connect to commutativity and why we choose 'easier' factors.",
    facilitationEt: "Poolitamine ja kahekordistamine on siin elegantne. Küsi: 'Kuidas tead, et 6×30 on lihtsam kui 12×15?' Seo kommutatiivsuse ja 'lihtsama' teguri valimisega.",
    commonMisconceptions: [
      "Halving and doubling: halving both numbers (6×7.5) instead of one",
      "Distributive: 12×10=120 but 12×5 computed as 12×5=50",
    ],
    commonMisconceptionsEt: [
      "Poolitamine ja kahekordistamine: poolitab mõlemat arvu (6×7.5) asemel ühte",
      "Jaotusseadus: 12×10=120 aga 12×5 arvutatakse kui 50",
    ],
    tags: ["korrutamine", "multiplication", "poolitamine", "kahekordistamine", "jaotusseadus"],
    pageRef: 52,
  },
  {
    slug: "korrutamine-25x18",
    title: "25 × 18",
    titleEt: "25 × 18",
    problem: "What is 25 × 18?",
    problemEt: "Mis on 25 × 18?",
    operation: "multiplication",
    gradeMin: 4,
    gradeMax: 6,
    difficulty: "hard",
    answer: "450",
    strategies: [
      {
        name: "Halving and doubling",
        nameEt: "Poolitamine ja kahekordistamine",
        description: "25×18 → 50×9=450",
        descriptionEt: "25×18 → 50×9=450",
        example: "25×2=50, 18÷2=9 → 50×9=450",
      },
      {
        name: "Quarter of 100 strategy",
        nameEt: "Veerandi strateegia",
        description: "25×18 = 100×18÷4 = 1800÷4 = 450",
        descriptionEt: "25×18 = 100×18÷4 = 1800÷4 = 450",
        example: "100×18=1800 → 1800÷4=450",
      },
    ],
    facilitation: "The 'quarter' strategy is surprising and powerful. Show both approaches on the board and let students decide which feels more natural.",
    facilitationEt: "Veerandi strateegia on üllatav ja võimas. Näita mõlemat lähenemist tahvlil ja lase õpilastel otsustada, kumb tundub loomulikum.",
    commonMisconceptions: [
      "Halving and doubling: doubling both (50×36=1800 — off by a factor of 4)",
    ],
    commonMisconceptionsEt: [
      "Poolitamine ja kahekordistamine: kahekordistab mõlemat (50×36=1800 — 4 korda liiga suur)",
    ],
    tags: ["korrutamine", "multiplication", "poolitamine", "veerand", "25"],
    pageRef: 54,
  },
  {
    slug: "korrutamine-8x125",
    title: "8 × 125",
    titleEt: "8 × 125",
    problem: "What is 8 × 125?",
    problemEt: "Mis on 8 × 125?",
    operation: "multiplication",
    gradeMin: 5,
    gradeMax: 6,
    difficulty: "medium",
    answer: "1000",
    strategies: [
      {
        name: "Eighth of 1000",
        nameEt: "Tuhande kaheksandik",
        description: "8 × 125 = 1000 because 1000 ÷ 8 = 125",
        descriptionEt: "8 × 125 = 1000, sest 1000 ÷ 8 = 125",
        example: "Think: 8 × 125 = 1000",
      },
      {
        name: "Repeated doubling",
        nameEt: "Korduv kahekordistamine",
        description: "1×125=125, 2×125=250, 4×125=500, 8×125=1000",
        descriptionEt: "1×125=125, 2×125=250, 4×125=500, 8×125=1000",
        example: "125→250→500→1000",
      },
    ],
    facilitation: "A beautiful 'landmark number' problem. Ask students: 'Have you seen 8 and 125 together before?' Connect to byte (8 bits) and kilobyte (1000 bytes) for older students.",
    facilitationEt: "Ilus 'maastikupunkti arvu' ülesanne. Küsi: 'Kas olete näinud 8 ja 125 koos varem?' Seosta baidiga (8 bitti) ja kilobaidiga (1000 baiti) vanematele õpilastele.",
    commonMisconceptions: [
      "8×125=8×100+8×25=800+175=975 (error in 8×25=175 instead of 200)",
    ],
    commonMisconceptionsEt: [
      "8×125=8×100+8×25=800+175=975 (viga 8×25=175 asemel 200)",
    ],
    tags: ["korrutamine", "multiplication", "1000", "kahekordistamine", "maastikupunkti-arvud"],
    pageRef: 58,
  },

  // ─── DIVISION ───────────────────────────────────────────────────────────────
  {
    slug: "jagamine-96-jagada-4",
    title: "96 ÷ 4",
    titleEt: "96 ÷ 4",
    problem: "What is 96 ÷ 4?",
    problemEt: "Mis on 96 ÷ 4?",
    operation: "division",
    gradeMin: 3,
    gradeMax: 5,
    difficulty: "medium",
    answer: "24",
    strategies: [
      {
        name: "Partial quotients",
        nameEt: "Osajagud",
        description: "80÷4=20, 16÷4=4, 20+4=24",
        descriptionEt: "80÷4=20, 16÷4=4, 20+4=24",
        example: "80÷4=20, 16÷4=4 → 24",
      },
      {
        name: "Halving",
        nameEt: "Poolitamine",
        description: "96÷4 = 96÷2÷2 = 48÷2 = 24",
        descriptionEt: "96÷4 = 96÷2÷2 = 48÷2 = 24",
        example: "96÷2=48 → 48÷2=24",
      },
      {
        name: "Think multiplication",
        nameEt: "Mõtle korrutamisena",
        description: "4×? = 96 → 4×20=80, 4×4=16, so 4×24=96",
        descriptionEt: "4×? = 96 → 4×20=80, 4×4=16, seega 4×24=96",
        example: "4×20=80, 4×4=16 → 4×24=96",
      },
    ],
    facilitation: "Halving is the star here — it turns division by 4 into two easier halvings. Compare all three methods and vote on which is most efficient.",
    facilitationEt: "Poolitamine on siin täht — see muudab jagamise 4-ga kaheks lihtsamaks poolitamiseks. Võrdle kõiki kolme meetodit ja hääleta kõige tõhusama üle.",
    commonMisconceptions: [
      "Partial quotients: 96-80=16 correct, but then 16÷4=3 (off-by-one error)",
      "Halving: 96÷2=48, then treating 48÷2 as 48-2=46",
    ],
    commonMisconceptionsEt: [
      "Osajagud: 96-80=16 on õige, aga siis 16÷4=3 (ühevõrra vale vastus)",
      "Poolitamine: 96÷2=48, siis 48÷2 käsitletakse kui 48-2=46",
    ],
    tags: ["jagamine", "division", "poolitamine", "osajagud", "mõtle-korrutamisena"],
    pageRef: 66,
  },
  {
    slug: "jagamine-132-jagada-6",
    title: "132 ÷ 6",
    titleEt: "132 ÷ 6",
    problem: "What is 132 ÷ 6?",
    problemEt: "Mis on 132 ÷ 6?",
    operation: "division",
    gradeMin: 4,
    gradeMax: 6,
    difficulty: "medium",
    answer: "22",
    strategies: [
      {
        name: "Partial quotients",
        nameEt: "Osajagud",
        description: "120÷6=20, 12÷6=2, 20+2=22",
        descriptionEt: "120÷6=20, 12÷6=2, 20+2=22",
        example: "120÷6=20, 12÷6=2 → 22",
      },
      {
        name: "Halving then thirds",
        nameEt: "Poolitamine ja kolmandamine",
        description: "132÷6 = 132÷2÷3 = 66÷3 = 22",
        descriptionEt: "132÷6 = 132÷2÷3 = 66÷3 = 22",
        example: "132÷2=66 → 66÷3=22",
      },
    ],
    facilitation: "Ask students to estimate first — is it closer to 20 or 25? Then compare the two strategies. Which decomposition of 6 (as 2×3 or as a divisor directly) was more natural?",
    facilitationEt: "Palu õpilastel kõigepealt hinnata — kas vastus on lähemal 20-le või 25-le? Siis võrdle kaht strateegiat. Kumb 6 lahutamine (2×3 või otse) oli loomulikum?",
    commonMisconceptions: [
      "Partial quotients: choosing 60÷6=10 first (correct but inefficient), needing more steps",
      "Halving: 132÷2=66, then treating 66÷3 as 66÷3=20 (off by rounding)",
    ],
    commonMisconceptionsEt: [
      "Osajagud: valib 60÷6=10 esimesena (õige, kuid ebaefektiivne)",
      "Poolitamine: 132÷2=66, siis 66÷3 käsitletakse kui 20 (ümardamise tõttu vale)",
    ],
    tags: ["jagamine", "division", "osajagud", "poolitamine", "3-kohaline"],
    pageRef: 70,
  },
  {
    slug: "jagamine-525-jagada-25",
    title: "525 ÷ 25",
    titleEt: "525 ÷ 25",
    problem: "What is 525 ÷ 25?",
    problemEt: "Mis on 525 ÷ 25?",
    operation: "division",
    gradeMin: 5,
    gradeMax: 6,
    difficulty: "hard",
    answer: "21",
    strategies: [
      {
        name: "Multiply by 4 (convert to ÷100)",
        nameEt: "Korruta 4-ga (muuda ÷100-ks)",
        description: "525÷25 = 2100÷100 = 21",
        descriptionEt: "525÷25 = 2100÷100 = 21",
        example: "525×4=2100, 2100÷100=21",
      },
      {
        name: "Think multiplication",
        nameEt: "Mõtle korrutamisena",
        description: "25×20=500, 500+25=525 so 25×21=525",
        descriptionEt: "25×20=500, 500+25=525 seega 25×21=525",
        example: "25×20=500, 25×1=25 → 25×21=525",
      },
    ],
    facilitation: "The 'multiply by 4' trick is surprising. Ask: 'Why does multiplying both numbers by 4 give the same answer?' This is a rich discussion about equivalent ratios.",
    facilitationEt: "'Korruta 4-ga' nipp on üllatav. Küsi: 'Miks mõlema arvu 4-ga korrutamine annab sama vastuse?' See on rikas arutelu ekvivalentsete suhete üle.",
    commonMisconceptions: [
      "Multiplying only the dividend by 4: 2100÷25=84 (wrong)",
      "Think multiplication: 25×21 computed as 525 but not recognized as the answer",
    ],
    commonMisconceptionsEt: [
      "Korrutab ainult jagatavat 4-ga: 2100÷25=84 (vale)",
      "Mõtle korrutamisena: 25×21 arvutatakse 525-ks, kuid ei tunnistata vastuseks",
    ],
    tags: ["jagamine", "division", "25", "ekvivalentsed-suhted", "mõtle-korrutamisena"],
    pageRef: 74,
  },
  {
    slug: "jagamine-300-jagada-12",
    title: "300 ÷ 12",
    titleEt: "300 ÷ 12",
    problem: "What is 300 ÷ 12?",
    problemEt: "Mis on 300 ÷ 12?",
    operation: "division",
    gradeMin: 4,
    gradeMax: 6,
    difficulty: "hard",
    answer: "25",
    strategies: [
      {
        name: "Partial quotients",
        nameEt: "Osajagud",
        description: "240÷12=20, 60÷12=5, 20+5=25",
        descriptionEt: "240÷12=20, 60÷12=5, 20+5=25",
        example: "240÷12=20, 60÷12=5 → 25",
      },
      {
        name: "Simplify the fraction",
        nameEt: "Lihtsusta murdu",
        description: "300÷12 = 150÷6 = 75÷3 = 25",
        descriptionEt: "300÷12 = 150÷6 = 75÷3 = 25",
        example: "300÷12 → 150÷6 → 75÷3 → 25",
      },
    ],
    facilitation: "The fraction simplification path (÷2 twice, ÷3) is powerful for students who see it. Ask: 'Is there an easier related problem?'",
    facilitationEt: "Murru lihtsustamise tee (÷2 kaks korda, ÷3) on võimas õpilastele, kes seda näevad. Küsi: 'Kas on lihtsam seotud ülesanne?'",
    commonMisconceptions: [
      "Partial quotients: 12×10=120, then confused about how much remains",
    ],
    commonMisconceptionsEt: [
      "Osajagud: 12×10=120, siis segadus, kui palju jääb alles",
    ],
    tags: ["jagamine", "division", "lihtsustamine", "osajagud"],
    pageRef: 72,
  },

  // ─── MIXED / ESTIMATION ──────────────────────────────────────────────────────
  {
    slug: "hindamine-493-pluss-312",
    title: "Estimate: 493 + 312",
    titleEt: "Hinda: 493 + 312",
    problem: "Without calculating exactly, is 493 + 312 closer to 700, 800, or 900?",
    problemEt: "Ilma täpselt arvutamata — kas 493 + 312 on lähemal 700-le, 800-le või 900-le?",
    operation: "addition",
    gradeMin: 3,
    gradeMax: 5,
    difficulty: "easy",
    answer: "800 (exact: 805)",
    strategies: [
      {
        name: "Front-end estimation",
        nameEt: "Esiosa hindamine",
        description: "400+300=700, then ~90+10=100 more → ~800",
        descriptionEt: "400+300=700, siis ~90+10=100 rohkem → ~800",
        example: "400+300=700 → +90+10≈800",
      },
      {
        name: "Round to nearest hundred",
        nameEt: "Ümarda lähima sajani",
        description: "500+300=800",
        descriptionEt: "500+300=800",
        example: "493≈500, 312≈300 → 800",
      },
    ],
    facilitation: "Estimation is often neglected. Ask students to commit to an estimate BEFORE any calculation. Discuss: what information did you use first?",
    facilitationEt: "Hindamist jäetakse sageli tähelepanuta. Palu õpilastel pühenduda hinnangule ENNE arvutamist. Arutle: millist infot kasutasid kõigepealt?",
    commonMisconceptions: [
      "Refusing to estimate without exact calculation — 'I need to add it properly'",
      "Rounding 493 down to 400 instead of up to 500",
    ],
    commonMisconceptionsEt: [
      "Keeldumine hindamast ilma täpse arvutamiseta — 'Ma pean seda korralikult liitma'",
      "493 allapoole ümardamine 400-ks asemel ülespoole 500-ks",
    ],
    tags: ["hindamine", "estimation", "addition", "ümardamine", "esiosa"],
    pageRef: 82,
  },
  {
    slug: "hindamine-korrutamine-49x21",
    title: "Estimate: 49 × 21",
    titleEt: "Hinda: 49 × 21",
    problem: "Without calculating exactly, estimate 49 × 21.",
    problemEt: "Ilma täpselt arvutamata, hinda 49 × 21.",
    operation: "multiplication",
    gradeMin: 4,
    gradeMax: 6,
    difficulty: "medium",
    answer: "~1000 (exact: 1029)",
    strategies: [
      {
        name: "Round both to friendly numbers",
        nameEt: "Ümarda mõlemad mugavateks arvudeks",
        description: "49≈50, 21≈20 → 50×20=1000",
        descriptionEt: "49≈50, 21≈20 → 50×20=1000",
        example: "50×20=1000",
      },
      {
        name: "One-number rounding",
        nameEt: "Ühe arvu ümardamine",
        description: "50×21=1050, which is close",
        descriptionEt: "50×21=1050, mis on lähedal",
        example: "50×21=1050≈1000",
      },
    ],
    facilitation: "Point out that rounding one vs both numbers gives slightly different estimates — and both are 'correct' as estimates. This builds number sense, not anxiety.",
    facilitationEt: "Juhi tähelepanu sellele, et ühe vs mõlema arvu ümardamine annab veidi erinevaid hinnanguid — ja mõlemad on hinnangutena 'õiged'. See arendab arvutunnetust, mitte ärevust.",
    commonMisconceptions: [
      "Over-rounding: 49→40, 21→20 → 800 (too low)",
      "Exact calculation anxiety: refusing to estimate",
    ],
    commonMisconceptionsEt: [
      "Üle-ümardamine: 49→40, 21→20 → 800 (liiga väike)",
      "Täpse arvutamise ärevus: keeldumine hindamisest",
    ],
    tags: ["hindamine", "estimation", "multiplication", "ümardamine"],
    pageRef: 84,
  },
  {
    slug: "segatehted-pool-kolmandik",
    title: "½ of 360 and ⅓ of 360",
    titleEt: "½ arvust 360 ja ⅓ arvust 360",
    problem: "What is half of 360? What is a third of 360? Which is larger?",
    problemEt: "Mis on pool arvust 360? Mis on kolmandik arvust 360? Kumb on suurem?",
    operation: "division",
    gradeMin: 4,
    gradeMax: 6,
    difficulty: "easy",
    answer: "180 and 120; half is larger",
    strategies: [
      {
        name: "Fraction as division",
        nameEt: "Murd kui jagamine",
        description: "½ of 360 = 360÷2 = 180; ⅓ of 360 = 360÷3 = 120",
        descriptionEt: "½ arvust 360 = 360÷2 = 180; ⅓ arvust 360 = 360÷3 = 120",
        example: "360÷2=180, 360÷3=120",
      },
      {
        name: "Reasoning about fractions",
        nameEt: "Murdudest arutlemine",
        description: "Half splits into 2 equal parts, third into 3 — more parts means smaller each, so ½ > ⅓",
        descriptionEt: "Pool jaguneb 2 võrdseks osaks, kolmandik 3-ks — rohkem osi tähendab väiksemaid osi, seega ½ > ⅓",
        example: "2 parts vs 3 parts → ½ > ⅓",
      },
    ],
    facilitation: "Use the clock (360°) as a real-world reference. Half a revolution vs. a third of a revolution. Ask students to show on a circle before calculating.",
    facilitationEt: "Kasuta kellakella (360°) päriselu viitena. Pool pööret vs kolmandik pööret. Palu õpilastel näidata ringil enne arvutamist.",
    commonMisconceptions: [
      "Thinking ⅓ > ½ because 3 > 2",
    ],
    commonMisconceptionsEt: [
      "Arvatakse ⅓ > ½, sest 3 > 2",
    ],
    tags: ["murrud", "fractions", "jagamine", "division", "pool", "kolmandik"],
    pageRef: 88,
  },
  {
    slug: "liitmine-arvu-moodustamine-makin-ten",
    title: "Making Ten: 8 + 5",
    titleEt: "Kümne täiendamine: 8 + 5",
    problem: "What is 8 + 5? Explain your thinking.",
    problemEt: "Mis on 8 + 5? Selgita oma mõtlemist.",
    operation: "addition",
    gradeMin: 1,
    gradeMax: 2,
    difficulty: "easy",
    answer: "13",
    strategies: [
      {
        name: "Making ten",
        nameEt: "Kümne täiendamine",
        description: "8 needs 2 to make 10, take 2 from 5: 8+2=10, then 10+3=13",
        descriptionEt: "8 vajab 2 kümne saamiseks, võta 5-st 2: 8+2=10, siis 10+3=13",
        example: "8+2=10, 10+3=13",
      },
      {
        name: "Counting on",
        nameEt: "Edasi loendamine",
        description: "Start at 8, count on 5: 9, 10, 11, 12, 13",
        descriptionEt: "Alusta 8-st, loendu 5 võrra edasi: 9, 10, 11, 12, 13",
        example: "8 → 9, 10, 11, 12, 13",
      },
      {
        name: "Using doubles",
        nameEt: "Paaritulede kasutamine",
        description: "Near double: 8+8=16, but 8+5 is 3 less: 16-3=13",
        descriptionEt: "Lähedane paaritud: 8+8=16, aga 8+5 on 3 vähem: 16-3=13",
        example: "8+8=16 → 16-3=13",
      },
    ],
    facilitation: "This is a foundational Number Talk. Use ten-frames on the board. Ask students to show where the '2' comes from in the making-ten strategy.",
    facilitationEt: "See on põhiline arvujututund. Kasuta tahvlil kümneraamistikke. Palu õpilastel näidata, kust tuleb '2' kümne täiendamise strateegias.",
    commonMisconceptions: [
      "Counting on from 5 instead of 8 (starting from the smaller addend)",
      "Making ten: 8+2=10 but then adding all of 5 instead of just 3",
    ],
    commonMisconceptionsEt: [
      "Loendamine 5-st asemel 8-st (alustamine väiksemast liidetavast)",
      "Kümne täiendamine: 8+2=10, aga siis liidab kogu 5 asemel ainult 3",
    ],
    tags: ["liitmine", "addition", "kümne-täiendamine", "making-ten", "1-klass", "2-klass", "kümneraam"],
    pageRef: 8,
  },
  {
    slug: "lahutamine-miinus-üheksa-nipp",
    title: "Subtract 9: 54 − 9",
    titleEt: "Lahuta 9: 54 − 9",
    problem: "What is 54 − 9?",
    problemEt: "Mis on 54 − 9?",
    operation: "subtraction",
    gradeMin: 2,
    gradeMax: 3,
    difficulty: "easy",
    answer: "45",
    strategies: [
      {
        name: "Minus 10, plus 1",
        nameEt: "Miinus 10, pluss 1",
        description: "54-10=44, 44+1=45",
        descriptionEt: "54-10=44, 44+1=45",
        example: "54-10=44 → 44+1=45",
      },
      {
        name: "Counting back",
        nameEt: "Tagasi loendamine",
        description: "54, 53, 52, 51, 50, 49, 48, 47, 46, 45",
        descriptionEt: "54, 53, 52, 51, 50, 49, 48, 47, 46, 45",
        example: "54 back 9 steps → 45",
      },
    ],
    facilitation: "Minus 10 plus 1 is a huge unlock for students stuck on counting back. Demonstrate: 'If I give you 10 less but then give 1 back, is that the same as 9 less?'",
    facilitationEt: "'Miinus 10, pluss 1' on suur avastus õpilastele, kes kinni jäävad tagasi loendamisele. Demonstreeri: 'Kui annan 10 vähem, aga siis annan 1 tagasi, kas see on sama mis 9 vähem?'",
    commonMisconceptions: [
      "Subtracting 10 and then subtracting 1 more (instead of adding 1): 44-1=43",
    ],
    commonMisconceptionsEt: [
      "Lahutab 10 ja siis lahutab veel 1 (asemel liitmist 1): 44-1=43",
    ],
    tags: ["lahutamine", "subtraction", "9", "kompensatsioon", "nipp"],
    pageRef: 24,
  },
] as const;
